-- Drop the tables if they exist
DROP TABLE NewWeapons CASCADE CONSTRAINTS;
DROP TABLE NewAmmunition CASCADE CONSTRAINTS;
DROP TABLE NewComponents CASCADE CONSTRAINTS;

-- Create the NewWeapons table
CREATE TABLE NewWeapons (
    weapon_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_type VARCHAR2(50),
    weapon_type VARCHAR2(50),
    heat NUMBER,
    damage NUMBER,
    min_range NUMBER,
    short_range NUMBER,
    medium_range NUMBER,
    long_range NUMBER,
    weight NUMBER,
    crit_slots NUMBER,
    ammo_needed VARCHAR2(3),
    location_restriction VARCHAR2(10)
);

-- Create the NewAmmunition table
CREATE TABLE NewAmmunition (
    ammo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weapon_id NUMBER REFERENCES NewWeapons(weapon_id),
    ammo_type VARCHAR2(50),
    rounds_per_ton NUMBER,
    ammo_tons NUMBER,
    ammo_space NUMBER
);

-- Create the NewComponents table
CREATE TABLE NewComponents (
    component_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50),
    weight NUMBER,
    crit_slots NUMBER,
    location_restriction VARCHAR2(10)
);

-- Insert data into NewWeapons table
--INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
--VALUES ('w_ballistic', 'AC 02', 1, 2, 4, 8, 16, 24, 6, 1, 'yes', NULL);

--INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
--VALUES ('w_ballistic', 'AC 05', 1, 5, 3, 6, 12, 18, 8, 4, 'yes', NULL);

--INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
--VALUES ('w_ballistic', 'AC 05 Ultra', 1, 5, 2, 6, 13, 20, 9, 5, 'yes', NULL);

--INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
--VALUES ('w_ballistic', 'AC 10', 3, 10, NULL, 5, 10, 15, 12, 7, 'yes', NULL);

-- Inner Sphere Ballistic Weapons
INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_ballistic', 'AC 02', 1, 2, 4, 8, 16, 24, 6, 1, 'yes', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_ballistic', 'AC 05', 1, 5, 3, 6, 12, 18, 8, 4, 'yes', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_ballistic', 'AC 05 Ultra', 1, 5, 2, 6, 13, 20, 9, 5, 'yes', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_ballistic', 'AC 10', 3, 10, NULL, 5, 10, 15, 12, 7, 'yes', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_ballistic', 'AC 10-X', 2, 10, NULL, 6, 12, 18, 11, 6, 'yes', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_ballistic', 'AC 20', 7, 20, NULL, 3, 6, 9, 14, 10, 'yes', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_ballistic', 'Anti-Missile', 1, NULL, NULL, NULL, NULL, NULL, 0.5, 1, 'yes', NULL);

-- Inner Sphere Artillery Weapons
INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_artillery', 'Arrow IV', 10, NULL, NULL, NULL, NULL, NULL, 15, 15, 'yes', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_artillery', 'Long Tom', 20, NULL, NULL, NULL, NULL, NULL, 30, 30, 'yes', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_artillery', 'Sniper', 10, NULL, NULL, NULL, NULL, NULL, 20, 20, 'yes', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_artillery', 'Thumper', 6, NULL, NULL, NULL, NULL, NULL, 15, 15, 'yes', NULL);

-- Inner Sphere Energy Weapons
INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_energy', 'Flamer', 3, 2, NULL, 1, 2, 3, 1, 1, 'no', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_energy', 'Flamer, Vehicle', 3, 2, NULL, 1, 2, 3, 0.5, 1, 'yes', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_energy', 'Laser ER Large', 12, 8, NULL, 7, 14, 19, 5, 2, 'no', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_energy', 'Laser Large', 8, 8, NULL, 5, 10, 15, 5, 2, 'no', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_energy', 'Laser Large Pulse', 10, 9, NULL, 3, 7, 10, 7, 2, 'no', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_energy', 'Laser Medium', 3, 5, NULL, 3, 6, 9, 1, 1, 'no', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_energy', 'Laser Medium Pulse', 4, 6, NULL, 2, 4, 6, 2, 1, 'no', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_energy', 'Laser Small', 1, 3, NULL, 1, 2, 3, 0.5, 1, 'no', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_energy', 'Laser Small Pulse', 2, 3, NULL, 1, 2, 3, 1, 1, 'no', NULL);

-- Inner Sphere Missile Weapons
INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_missile', 'LRM05', 2, NULL, 6, 7, 14, 21, 2, 1, 'yes', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_missile', 'LRM10', 4, NULL, 6, 7, 14, 21, 5, 2, 'yes', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_missile', 'LRM15', 5, NULL, 6, 7, 14, 21, 7, 3, 'yes', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_missile', 'LRM20', 6, NULL, 6, 7, 14, 21, 10, 5, 'yes', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_missile', 'SRM2', 2, NULL, NULL, 3, 6, 9, 1, 1, 'yes', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_missile', 'SRM2 Streak', 2, NULL, NULL, 3, 6, 9, 1.5, 1, 'yes', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_missile', 'SRM4', 3, NULL, NULL, 3, 6, 9, 2, 1, 'yes', NULL);

INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_missile', 'SRM6', 4, NULL, NULL, 3, 6, 9, 3, 2, 'yes', NULL);

-- Inner Sphere Ballistic Weapon (Additional)
INSERT INTO NewWeapons (group_type, weapon_type, heat, damage, min_range, short_range, medium_range, long_range, weight, crit_slots, ammo_needed, location_restriction) 
VALUES ('w_ballistic', 'MG', 0, 2, NULL, 1, 2, 3, 0.5, 1, 'yes', NULL);


-- Insert data into NewAmmunition table
--INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
--VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'AC 02'), 'AC 02', 45, 1, 1);

--INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
--VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'AC 05'), 'AC 05', 20, 1, 1);

--INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
--VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'AC 05 Ultra'), 'AC 05 Ultra', 20, 1, 1);

-- Insert data into NewComponents table
--INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
--VALUES ('Artemis IV FCS', 1, 1, NULL);

--INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
--VALUES ('Beagle', 1.5, 2, NULL);
-- Inner Sphere Ammunition
INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'AC 02'), 'AC 02', 45, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'AC 05'), 'AC 05', 20, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'AC 05 Ultra'), 'AC 05 Ultra', 20, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'AC 10'), 'AC 10', 10, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'AC 10-X'), 'AC 10-X', 10, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'AC 10-X Cluster'), 'AC 10-X Cluster', 10, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'AC 20'), 'AC 20', 5, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'Anti-Missile'), 'Anti-Missile IS', 12, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'Arrow IV'), 'Arrow IV Std', 5, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'Arrow IV'), 'Arrow IV Homer', 5, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'Gauss Rifle'), 'Gauss Rifle', 8, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'Long Tom'), 'Long Tom', 5, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'Long Tom Thunder'), 'Long Tom Thunder', 5, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'LRM05'), 'LRM05', 24, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'LRM05'), 'LRM05 Swarm', 24, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'LRM05'), 'LRM05 Thunder', 24, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'LRM10'), 'LRM10', 12, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'LRM10'), 'LRM10 Swarm', 12, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'LRM10'), 'LRM10 Thunder', 12, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'LRM15'), 'LRM15', 8, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'LRM15'), 'LRM15 Swarm', 8, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'LRM15'), 'LRM15 Thunder', 8, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'LRM20'), 'LRM20', 6, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'LRM20'), 'LRM20 Swarm', 6, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'LRM20'), 'LRM20 Thunder', 6, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'MG'), 'MG', 200, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'NARC'), 'NARC', 6, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'Sniper'), 'Sniper', 10, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'Sniper'), 'Sniper Thunder', 10, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'SRM2'), 'SRM2', 50, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'SRM2'), 'SRM2 Inferno', 50, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'SRM2 Streak'), 'SRM2 Streak', 50, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'SRM4'), 'SRM4', 25, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'SRM6'), 'SRM6', 15, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'Thumper'), 'Thumper', 20, 1, 1);

INSERT INTO NewAmmunition (weapon_id, ammo_type, rounds_per_ton, ammo_tons, ammo_space)
VALUES ((SELECT weapon_id FROM NewWeapons WHERE weapon_type = 'Thumper'), 'Thumper Thunder', 20, 1, 1);

-- Inner Sphere Components
INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('Artemis IV FCS', 1, 1, NULL);

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('Beagle', 1.5, 2, NULL);

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('C3 Comp', 5, 5, NULL);

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('C3 Slave', 1, 1, NULL);

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('CASE', 0.5, 1, NULL);

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('Guardian ECM', 1.5, 2, NULL);

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('MASC', NULL, NULL, NULL);  -- MASC weight is variable based on tonnage, adjust accordingly

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('Std HS', 1, 1, NULL);

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('x2 HS', 1, 3, NULL);

-- Insert actuators
INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('L Hand Act', 0, 1, 'LA');

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('L Low Act', 0, 1, 'LA');

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('L Up Act', 0, 1, 'LA');

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('R Hand Act', 0, 1, 'RA');

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('R Low Act', 0, 1, 'RA');

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('R Up Act', 0, 1, 'RA');

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('Shoulders', 0, 2, 'LS RS');

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('Legs', 0, 8, 'LL RL');

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('Leg LFrt (quad)', 0, 4, 'LL');

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('Leg LRear (quad)', 0, 4, 'LL');

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('Leg RFrt (quad)', 0, 4, 'RL');

INSERT INTO NewComponents (name, weight, crit_slots, location_restriction)
VALUES ('Leg RRear (quad)', 0, 4, 'RL');
