INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (505919, 'Atlas', 'AS7-K', '144', '100', 'Sniper', 'Biped', 'Inner Sphere', '3049', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (505919, 505919, '300 XL Engine', 'Standard', 'Standard', '20 Single', '3', '0');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (505919, 505919, 'Standard Armor', 'LA Armor', '34');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (505919, 505919, 'Standard Armor', 'RA Armor', '34');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (505919, 505919, 'Standard Armor', 'LT Armor', '32');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (505919, 505919, 'Standard Armor', 'RT Armor', '32');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (505919, 505919, 'Standard Armor', 'CT Armor', '47');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (505919, 505919, 'Standard Armor', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (505919, 505919, 'Standard Armor', 'LL Armor', '41');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (505919, 505919, 'Standard Armor', 'RL Armor', '41');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (505919, 505919, 'Standard Armor', 'RTL Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (505919, 505919, 'Standard Armor', 'RTR Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (505919, 505919, 'Standard Armor', 'RTC Armor', '14');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5059191, 505919, '1 ISGaussRifle', 'Right Torso', Ammo:16);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5059192, 505919, '1 ISLRM20', 'Left Torso', Ammo:12);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5059193, 505919, '1 ISERLargeLaser', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5059194, 505919, '1 ISERLargeLaser', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5059195, 505919, '2 ISMediumPulseLaser', 'Center Torso (R)', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5059196, 505919, '1 ISAntiMissileSystem', 'Left Arm', Ammo:12);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (5059191, 505919, 'battle_fists_la');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059191, 505919, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059192, 505919, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059193, 505919, 'Left Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059194, 505919, 'Left Arm', 'Hand Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059195, 505919, 'Left Arm', 'Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059196, 505919, 'Left Arm', 'Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059197, 505919, 'Left Arm', 'ISERLargeLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059198, 505919, 'Left Arm', 'ISERLargeLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059199, 505919, 'Left Arm', 'ISAntiMissileSystem');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059200, 505919, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059201, 505919, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059202, 505919, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059203, 505919, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059204, 505919, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059205, 505919, 'Right Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059206, 505919, 'Right Arm', 'Hand Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059207, 505919, 'Right Arm', 'Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059208, 505919, 'Right Arm', 'Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059209, 505919, 'Right Arm', 'ISERLargeLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059210, 505919, 'Right Arm', 'ISERLargeLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059211, 505919, 'Right Arm', 'ISGauss Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059212, 505919, 'Right Arm', 'ISGauss Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059213, 505919, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059214, 505919, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059215, 505919, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059216, 505919, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059217, 505919, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059218, 505919, 'Left Torso', 'ISLRM20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059219, 505919, 'Left Torso', 'ISLRM20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059220, 505919, 'Left Torso', 'ISLRM20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059221, 505919, 'Left Torso', 'ISLRM20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059222, 505919, 'Left Torso', 'ISLRM20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059223, 505919, 'Left Torso', 'ISLRM20 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059224, 505919, 'Left Torso', 'ISLRM20 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059225, 505919, 'Left Torso', 'ISAMS Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059226, 505919, 'Left Torso', 'ISCASE');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059227, 505919, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059228, 505919, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059229, 505919, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059230, 505919, 'Right Torso', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059231, 505919, 'Right Torso', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059232, 505919, 'Right Torso', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059233, 505919, 'Right Torso', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059234, 505919, 'Right Torso', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059235, 505919, 'Right Torso', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059236, 505919, 'Right Torso', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059237, 505919, 'Right Torso', 'ISCASE');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059238, 505919, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059239, 505919, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059240, 505919, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059241, 505919, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059242, 505919, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059243, 505919, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059244, 505919, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059245, 505919, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059246, 505919, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059247, 505919, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059248, 505919, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059249, 505919, 'Center Torso', 'ISMediumPulseLaser (R)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059250, 505919, 'Center Torso', 'ISMediumPulseLaser (R)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059251, 505919, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059252, 505919, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059253, 505919, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059254, 505919, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059255, 505919, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059256, 505919, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059257, 505919, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059258, 505919, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059259, 505919, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059260, 505919, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059261, 505919, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059262, 505919, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059263, 505919, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059264, 505919, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059265, 505919, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059266, 505919, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059267, 505919, 'Left Leg', 'Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059268, 505919, 'Left Leg', 'Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059269, 505919, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059270, 505919, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059271, 505919, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059272, 505919, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059273, 505919, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059274, 505919, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059275, 505919, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059276, 505919, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059277, 505919, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059278, 505919, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059279, 505919, 'Right Leg', 'Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059280, 505919, 'Right Leg', 'Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059281, 505919, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059282, 505919, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059283, 505919, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059284, 505919, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059285, 505919, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5059286, 505919, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (505919, 505919, "Yori 'Mech Works,Independence Weaponry", "Al Na'ir,Quentin", 'CHASSIS:Foundation Type 10X');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (505919, 505919, "A ''Mech as powerful as possible, as impenetrable as possible, and as ugly and foreboding as conceivable, so that fear itself will be our ally.”-Aleksandr Kerensky", 'The Atlas is probably the best-known BattleMech to ever set foot on the modern battlefield. Designed with specifications from Aleksandr Kerensky himself in 2755 in the midst of the Cameron Edicts, the Atlas was originally intended to ensure SLDF superiority over the Star League member states. Carrying the largest LRM launcher, the largest autocannon, and the largest SRM launcher possible, the Atlas can deal frightening amounts of damage in short amounts of time. Often used as a command vehicle, the Atlas mounts an advanced antenna and communications array, allowing it to engage in surface-to-space communications in real time. The massive 19-ton hide of armor that protects the Atlas makes it a difficult foe to take down. Indeed, most MechWarriors choose to fall back rather than face one head-on, as its lumbering gait means it can rarely catch up to other \'\'Mechs that choose to flee it. A full year of development went into crafting the famous "Death\'\'s Head" of the \'\'Mech to achieve the perfect ratio of functionality and fear. The head is also quite roomy and allows a small satellite dish to be mounted for surface-to-space communications. During combat the pilot can easily fold up the dish and store it within a protective portion of the head.', "A 3050''s Combine upgrade of the Atlas that used rediscovered Star League technology, the K model was built with a Vlar 300 XL Engine. Carrying a Shigunga LRM-20 with two tons of ammo in the left torso the ''Mech was rearmed for long range combat with an Imperator Dragon''s Fire Gauss Rifle in place of the autocannon, with two tons of gauss rounds carried in the right arm, backed up by a pair of Victory Nickel Alloy ER Large Lasers split between both arms. This armament allowed the AS7-K to keep an enemy at range, though the continued use of twenty single heat sinks caused swift heat buildup if both lasers are fired repeatedly. For close range defense, the K model carried two Victory Heartbeat Medium Pulse Lasers in the rear torso and a Yori Flyswatter Anti-Missile System in the left arm with one ton of reloads in the left torso. To round off the AS7-K''s defense, CASE was added to the side torsos to protect against an ammunition explosion.", 'Though the inexorable arming of the Great Houses continued, the Atlas proved itself to be everything General Kerensky requested. With the largest amount of armor of nearly any \'\'Mech, crippling firepower, and the foreboding skull-shaped "Death\'\'s Head" cockpit/head assembly, the Atlas lived up to its reputation. The mere sight of an Atlas had been known to make even a veteran MechWarrior break out in a cold sweat, and theoretically a single Atlas can take on and wipe out an entire battalion of Stingers in exchange for minor armor loss. The Atlas\'\' first combat trials came during the Amaris Civil War, where it served an instrumental role as a powerful command vehicle. Though General Kerensky is well-known for being the one who kicked down the palace doors of the Usurper in his Orion, it was his close friend Aaron DeChavilier who, in his Atlas, weathered the storm of enemy fire and breached the protective wall surrounding the complex. After this conflict it was therefore with little surprise that the General wished for all of these \'\'Mechs to accompany him on Operation Exodus, but ironically of those MechWarriors who refused his summons fully two-thirds were Atlas pilots. These units were spread among the Successor States and Atlas factories on Al Na\'\'ir, Hesperus II and Quentin would continue production of the \'\'Mech through the Succession Wars. Most commanders were loath to tamper too much with such a successful \'\'Mech, but the recovery of the Helm Memory Core resulted in a number of ancient designs being updated with lostech, and the Atlas was no exception. The new AS7-K model was released in 3049, just in time to fight off the Clan Invasion. The Federated Commonwealth also briefly began production of their own model, the AS7-S, although following the civil war that line was discontinued and further variants have been introduced by the Lyran Alliance and Draconis Combine. Despite its age, well into the end of the thirty-first century there were no plans to replace the Atlas, and even the most cutting-edge designs will stop and pause when faced with the prospect of an Atlas bearing down on them.');