INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (800942, 'Axman', 'AXM-2N', '185', None, 'Skirmisher', 'Biped', None, None, None, None);
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (800942, 800942, None, None, None, None, None, None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (8009421, 800942, 'Large Pulse Laser', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (8009422, 800942, 'Medium Laser', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (8009423, 800942, 'Medium Laser', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (8009424, 800942, 'Medium Laser', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (8009425, 800942, 'LRM 15', 'Left Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (8009426, 800942, 'LRM 15', 'Right Torso', NULL);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (8009421, 800942, 'pro_actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009421, 800942, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009422, 800942, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009423, 800942, 'Left Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009424, 800942, 'Left Arm', 'Hand Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009425, 800942, 'Left Arm', 'ISLargePulseLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009426, 800942, 'Left Arm', 'ISLargePulseLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009427, 800942, 'Left Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009428, 800942, 'Left Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009429, 800942, 'Left Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009430, 800942, 'Left Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009431, 800942, 'Left Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009432, 800942, 'Left Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009433, 800942, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009434, 800942, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009435, 800942, 'Right Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009436, 800942, 'Right Arm', 'Hand Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009437, 800942, 'Right Arm', 'Hatchet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009438, 800942, 'Right Arm', 'Hatchet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009439, 800942, 'Right Arm', 'Hatchet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009440, 800942, 'Right Arm', 'Hatchet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009441, 800942, 'Right Arm', 'Hatchet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009442, 800942, 'Right Arm', 'Medium Laser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009443, 800942, 'Right Arm', 'Medium Laser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009444, 800942, 'Right Arm', 'Medium Laser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009445, 800942, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009446, 800942, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009447, 800942, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009448, 800942, 'Left Torso', 'LRM 15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009449, 800942, 'Left Torso', 'LRM 15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009450, 800942, 'Left Torso', 'LRM 15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009451, 800942, 'Left Torso', 'IS Ammo LRM-15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009452, 800942, 'Left Torso', 'IS Ammo LRM-15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009453, 800942, 'Left Torso', 'ISCASE');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009454, 800942, 'Left Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009455, 800942, 'Left Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009456, 800942, 'Left Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009457, 800942, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009458, 800942, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009459, 800942, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009460, 800942, 'Right Torso', 'LRM 15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009461, 800942, 'Right Torso', 'LRM 15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009462, 800942, 'Right Torso', 'LRM 15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009463, 800942, 'Right Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009464, 800942, 'Right Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009465, 800942, 'Right Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009466, 800942, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009467, 800942, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009468, 800942, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009469, 800942, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009470, 800942, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009471, 800942, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009472, 800942, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009473, 800942, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009474, 800942, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009475, 800942, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009476, 800942, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009477, 800942, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009478, 800942, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009479, 800942, 'Center Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009480, 800942, 'Center Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009481, 800942, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009482, 800942, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009483, 800942, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009484, 800942, 'Head', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009485, 800942, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009486, 800942, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009487, 800942, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009488, 800942, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009489, 800942, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009490, 800942, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009491, 800942, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009492, 800942, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009493, 800942, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009494, 800942, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009495, 800942, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009496, 800942, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009497, 800942, 'Left Leg', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009498, 800942, 'Left Leg', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009499, 800942, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009500, 800942, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009501, 800942, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009502, 800942, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009503, 800942, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009504, 800942, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009505, 800942, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009506, 800942, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009507, 800942, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009508, 800942, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009509, 800942, 'Right Leg', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009510, 800942, 'Right Leg', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009511, 800942, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009512, 800942, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009513, 800942, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009514, 800942, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009515, 800942, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8009516, 800942, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (800942, 800942, 'Defiance Industries,Johnston Industries', 'Furillo,New Syrtis', 'CHASSIS:Dorwinion AXM Standard');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (800942, 800942, "Developed by Team Banzai as the big brother of the highly successful Hatchetman, the Axman was designed exclusively to be a ''Mech killer", "The Axman has a ground speed of only 64.8 km/h, which is average for a Heavy weight, but improved in part by the inclusion of Jump Jets. The ''Mech is covered with eleven tons of Ferro-Fibrous armor that gives it a great deal of protection, with ten Double Heat Sinks offering average heat dissipation. Much like its lighter brother, the Axman was designed to utilize the Full-Head Ejection System to safe-guard its MechWarrior.", "The 2N variant of the Axman, introduced in the late 3040s, has been called a mistake by some and a stroke of genius by others. The 2N carries two LRM-15 launchers in place of the massive Autocannon/20 as the autocannon often jammed on early models. While this changes the ''Mech''s role from a city fighter to a long-range bombardment ''Mech, it also allows the Axman to be a support ''Mech that can defend itself with its massive Hatchet at ranges where the LRMs are ineffective if an enemy closes.", 'The Axman was also intended as a symbol of solidarity throughout the Federated Commonwealth by using components that were produced in Federated Suns, Lyran Commonwealth, and even former Capellan Confederation space. The collapse of the Federated Commonwealth in 3057 almost rendered the design extinct because of this, production slowing to a trickle as both the Federated Suns and Lyran Alliance were forced to rely on surplus stores while developing new variants utilizing locally sourced components.');