INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (771444, 'Axman', 'AXM-4D', '188', None, 'Brawler', 'Biped', None, None, None, None);
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (771444, 771444, None, None, None, None, None, None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7714441, 771444, 'Medium Laser', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7714442, 771444, 'Medium Laser', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7714443, 771444, 'Light AC/5', 'Left Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7714444, 771444, 'Light AC/5', 'Left Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7714445, 771444, 'Light AC/5', 'Right Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7714446, 771444, 'Light AC/5', 'Right Torso', None);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (7714441, 771444, 'pro_actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714441, 771444, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714442, 771444, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714443, 771444, 'Left Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714444, 771444, 'Left Arm', 'Hand Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714445, 771444, 'Left Arm', 'Medium Laser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714446, 771444, 'Left Arm', 'Medium Laser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714447, 771444, 'Left Arm', 'ISTargeting Computer');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714448, 771444, 'Left Arm', 'ISTargeting Computer');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714449, 771444, 'Left Arm', 'ISTargeting Computer');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714450, 771444, 'Left Arm', 'ISTargeting Computer');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714451, 771444, 'Left Arm', 'ISTargeting Computer');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714452, 771444, 'Left Arm', 'ISTargeting Computer');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714453, 771444, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714454, 771444, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714455, 771444, 'Right Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714456, 771444, 'Right Arm', 'Hand Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714457, 771444, 'Right Arm', 'Hatchet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714458, 771444, 'Right Arm', 'Hatchet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714459, 771444, 'Right Arm', 'Hatchet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714460, 771444, 'Right Arm', 'Hatchet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714461, 771444, 'Right Arm', 'Hatchet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714462, 771444, 'Right Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714463, 771444, 'Right Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714464, 771444, 'Right Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714465, 771444, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714466, 771444, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714467, 771444, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714468, 771444, 'Left Torso', 'Light Auto Cannon/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714469, 771444, 'Left Torso', 'Light Auto Cannon/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714470, 771444, 'Left Torso', 'Light Auto Cannon/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714471, 771444, 'Left Torso', 'Light Auto Cannon/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714472, 771444, 'Left Torso', 'IS Ammo LAC/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714473, 771444, 'Left Torso', 'IS Ammo LAC/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714474, 771444, 'Left Torso', 'ISCASE');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714475, 771444, 'Left Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714476, 771444, 'Left Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714477, 771444, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714478, 771444, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714479, 771444, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714480, 771444, 'Right Torso', 'Light Auto Cannon/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714481, 771444, 'Right Torso', 'Light Auto Cannon/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714482, 771444, 'Right Torso', 'Light Auto Cannon/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714483, 771444, 'Right Torso', 'Light Auto Cannon/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714484, 771444, 'Right Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714485, 771444, 'Right Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714486, 771444, 'Right Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714487, 771444, 'Right Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714488, 771444, 'Right Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714489, 771444, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714490, 771444, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714491, 771444, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714492, 771444, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714493, 771444, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714494, 771444, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714495, 771444, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714496, 771444, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714497, 771444, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714498, 771444, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714499, 771444, 'Center Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714500, 771444, 'Center Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714501, 771444, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714502, 771444, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714503, 771444, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714504, 771444, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714505, 771444, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714506, 771444, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714507, 771444, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714508, 771444, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714509, 771444, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714510, 771444, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714511, 771444, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714512, 771444, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714513, 771444, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714514, 771444, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714515, 771444, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714516, 771444, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714517, 771444, 'Left Leg', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714518, 771444, 'Left Leg', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714519, 771444, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714520, 771444, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714521, 771444, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714522, 771444, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714523, 771444, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714524, 771444, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714525, 771444, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714526, 771444, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714527, 771444, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714528, 771444, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714529, 771444, 'Right Leg', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714530, 771444, 'Right Leg', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714531, 771444, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714532, 771444, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714533, 771444, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714534, 771444, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714535, 771444, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7714536, 771444, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (771444, 771444, 'Johnston Industries', 'New Syrtis', 'CHASSIS:Dorwinion AXM Standard');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (771444, 771444, "Developed by Team Banzai as the big brother of the highly successful Hatchetman, the Axman was designed exclusively to be a 'Mech killer", "The Axman has a ground speed of only 64.8 km/h, which is average for a Heavy weight, but improved in part by the inclusion of Jump Jets. The 'Mech is covered with eleven tons of Ferro-Fibrous armor that gives it a great deal of protection, with ten Double Heat Sinks offering average heat dissipation. Much like its lighter brother, the Axman was designed to utilize the Full-Head Ejection System to safe-guard its MechWarrior.", "An attempt to reduce reliance upon foreign equipment, this exclusively Davion variant replaced the 1N line on New Syrtis in 3071. It drops the jump jets, lasers, and large-bore autocannon in favor of four Light Autocannon/5s, supplemented by two medium lasers. Two tons of ammunition stored in a CASE protected bay allows for some flexibility in the choice of munitions. A Targeting Computer improves the accuracy of all the weapons on the 'Mech. It uses Ferro-Fibrous armor for protection.", 'The Axman was also intended as a symbol of solidarity throughout the Federated Commonwealth by using components that were produced in Federated Suns, Lyran Commonwealth, and even former Capellan Confederation space. The collapse of the Federated Commonwealth in 3057 almost rendered the design extinct because of this, production slowing to a trickle as both the Federated Suns and Lyran Alliance were forced to rely on surplus stores while developing new variants utilizing locally sourced components.');