INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (220659, 'Berserker', 'BRZ-A3', '329', '100', 'Juggernaut', 'Biped', 'Inner Sphere', '3056', '2', 'TRO: 3055');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (220659, 220659, '400 XL Engine', 'Endo Steel', 'Standard', '16 Double', '4', '0');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (220659, 220659, 'Standard(Inner Sphere)', 'LA Armor', '34');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (220659, 220659, 'Standard(Inner Sphere)', 'RA Armor', '34');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (220659, 220659, 'Standard(Inner Sphere)', 'LT Armor', '31');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (220659, 220659, 'Standard(Inner Sphere)', 'RT Armor', '31');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (220659, 220659, 'Standard(Inner Sphere)', 'CT Armor', '46');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (220659, 220659, 'Standard(Inner Sphere)', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (220659, 220659, 'Standard(Inner Sphere)', 'LL Armor', '38');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (220659, 220659, 'Standard(Inner Sphere)', 'RL Armor', '38');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (220659, 220659, 'Standard(Inner Sphere)', 'RTL Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (220659, 220659, 'Standard(Inner Sphere)', 'RTR Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (220659, 220659, 'Standard(Inner Sphere)', 'RTC Armor', '15');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2206591, 220659, 'ER PPC', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2206592, 220659, 'Large Pulse Laser', 'Left Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2206593, 220659, 'Large Pulse Laser', 'Right Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2206594, 220659, 'AMS', 'Center Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2206595, 220659, 'Flamer', 'Head', None);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (2206591, 220659, 'distracting');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206591, 220659, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206592, 220659, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206593, 220659, 'Left Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206594, 220659, 'Left Arm', 'ISERPPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206595, 220659, 'Left Arm', 'ISERPPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206596, 220659, 'Left Arm', 'ISERPPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206597, 220659, 'Left Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206598, 220659, 'Left Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206599, 220659, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206600, 220659, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206601, 220659, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206602, 220659, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206603, 220659, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206604, 220659, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206605, 220659, 'Right Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206606, 220659, 'Right Arm', 'Hand Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206607, 220659, 'Right Arm', 'Hatchet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206608, 220659, 'Right Arm', 'Hatchet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206609, 220659, 'Right Arm', 'Hatchet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206610, 220659, 'Right Arm', 'Hatchet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206611, 220659, 'Right Arm', 'Hatchet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206612, 220659, 'Right Arm', 'Hatchet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206613, 220659, 'Right Arm', 'Hatchet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206614, 220659, 'Right Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206615, 220659, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206616, 220659, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206617, 220659, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206618, 220659, 'Left Torso', 'ISLargePulseLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206619, 220659, 'Left Torso', 'ISLargePulseLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206620, 220659, 'Left Torso', 'ISMASC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206621, 220659, 'Left Torso', 'ISMASC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206622, 220659, 'Left Torso', 'ISMASC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206623, 220659, 'Left Torso', 'ISMASC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206624, 220659, 'Left Torso', 'ISMASC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206625, 220659, 'Left Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206626, 220659, 'Left Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206627, 220659, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206628, 220659, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206629, 220659, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206630, 220659, 'Right Torso', 'ISLargePulseLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206631, 220659, 'Right Torso', 'ISLargePulseLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206632, 220659, 'Right Torso', 'ISGuardianECMSuite');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206633, 220659, 'Right Torso', 'ISGuardianECMSuite');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206634, 220659, 'Right Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206635, 220659, 'Right Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206636, 220659, 'Right Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206637, 220659, 'Right Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206638, 220659, 'Right Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206639, 220659, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206640, 220659, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206641, 220659, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206642, 220659, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206643, 220659, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206644, 220659, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206645, 220659, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206646, 220659, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206647, 220659, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206648, 220659, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206649, 220659, 'Center Torso', 'ISAntiMissileSystem');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206650, 220659, 'Center Torso', 'ISAMS Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206651, 220659, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206652, 220659, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206653, 220659, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206654, 220659, 'Head', 'Flamer');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206655, 220659, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206656, 220659, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206657, 220659, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206658, 220659, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206659, 220659, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206660, 220659, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206661, 220659, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206662, 220659, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206663, 220659, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206664, 220659, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206665, 220659, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206666, 220659, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206667, 220659, 'Left Leg', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206668, 220659, 'Left Leg', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206669, 220659, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206670, 220659, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206671, 220659, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206672, 220659, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206673, 220659, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2206674, 220659, 'Left Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (220659, 220659, None, None, None);
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (220659, 220659, None, None, None, None);