INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (32581, 'Blackjack', 'BJ-4', '389', '45', 'Brawler', 'Biped', 'Inner Sphere', '3067', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (32581, 32581, '180 Light Engine', 'Standard', 'Standard', '10 Double', '4', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (32581, 32581, 'Light Ferro-Fibrous', 'LA Armor', '12');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (32581, 32581, 'Light Ferro-Fibrous', 'RA Armor', '12');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (32581, 32581, 'Light Ferro-Fibrous', 'LT Armor', '15');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (32581, 32581, 'Light Ferro-Fibrous', 'RT Armor', '15');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (32581, 32581, 'Light Ferro-Fibrous', 'CT Armor', '18');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (32581, 32581, 'Light Ferro-Fibrous', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (32581, 32581, 'Light Ferro-Fibrous', 'LL Armor', '17');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (32581, 32581, 'Light Ferro-Fibrous', 'RL Armor', '17');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (32581, 32581, 'Light Ferro-Fibrous', 'RTL Armor', '6');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (32581, 32581, 'Light Ferro-Fibrous', 'RTR Armor', '6');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (32581, 32581, 'Light Ferro-Fibrous', 'RTC Armor', '8');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (325811, 32581, '1 ISLAC5', 'Right Arm', 'Ammo:80');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (325812, 32581, '1 ISERMediumLaser', 'Right Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (325813, 32581, '1 ISLAC5', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (325814, 32581, '1 ISERMediumLaser', 'Left Arm', None);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (325811, 32581, 'bad_rep_is');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325811, 32581, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325812, 32581, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325813, 32581, 'Left Arm', 'ISLAC5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325814, 32581, 'Left Arm', 'ISLAC5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325815, 32581, 'Left Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325816, 32581, 'Left Arm', 'Light Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325817, 32581, 'Left Arm', 'Light Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325818, 32581, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325819, 32581, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325820, 32581, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325821, 32581, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325822, 32581, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325823, 32581, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325824, 32581, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325825, 32581, 'Right Arm', 'ISLAC5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325826, 32581, 'Right Arm', 'ISLAC5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325827, 32581, 'Right Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325828, 32581, 'Right Arm', 'Light Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325829, 32581, 'Right Arm', 'Light Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325830, 32581, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325831, 32581, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325832, 32581, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325833, 32581, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325834, 32581, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325835, 32581, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325836, 32581, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325837, 32581, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325838, 32581, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325839, 32581, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325840, 32581, 'Left Torso', 'ISTargeting Computer');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325841, 32581, 'Left Torso', 'ISTargeting Computer');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325842, 32581, 'Left Torso', 'ISTargeting Computer');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325843, 32581, 'Left Torso', 'ISLAC5 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325844, 32581, 'Left Torso', 'ISLAC5 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325845, 32581, 'Left Torso', 'ISCASE');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325846, 32581, 'Left Torso', 'Light Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325847, 32581, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325848, 32581, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325849, 32581, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325850, 32581, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325851, 32581, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325852, 32581, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325853, 32581, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325854, 32581, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325855, 32581, 'Right Torso', 'ISLAC5 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325856, 32581, 'Right Torso', 'ISLAC5 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325857, 32581, 'Right Torso', 'ISCASE');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325858, 32581, 'Right Torso', 'Light Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325859, 32581, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325860, 32581, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325861, 32581, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325862, 32581, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325863, 32581, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325864, 32581, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325865, 32581, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325866, 32581, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325867, 32581, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325868, 32581, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325869, 32581, 'Center Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325870, 32581, 'Center Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325871, 32581, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325872, 32581, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325873, 32581, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325874, 32581, 'Head', 'Light Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325875, 32581, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325876, 32581, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325877, 32581, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325878, 32581, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325879, 32581, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325880, 32581, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325881, 32581, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325882, 32581, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325883, 32581, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325884, 32581, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325885, 32581, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325886, 32581, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325887, 32581, 'Left Leg', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325888, 32581, 'Left Leg', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325889, 32581, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325890, 32581, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325891, 32581, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325892, 32581, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325893, 32581, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325894, 32581, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325895, 32581, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325896, 32581, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325897, 32581, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325898, 32581, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325899, 32581, 'Right Leg', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325900, 32581, 'Right Leg', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325901, 32581, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325902, 32581, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325903, 32581, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325904, 32581, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325905, 32581, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (325906, 32581, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (32581, 32581, 'General Motors', 'Talcott', 'CHASSIS:GM BJ-1');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (32581, 32581, 'The original contract between General Motors and the SLDF sought for "a medium BattleMech with insurrection suppression and fire-support capabilities." The outcome was the Blackjack. Despite meeting all of its production requirements, the Blackjack gained an unjust reputation and was rejected by the Star League.', "The Blackjack's original mission was to assist in suppressing insurgent groups (mostly in the Periphery) that defied Star League authority in the decades preceding its demise. The Blackjack is only a minor success in its secondary capacity as a fire support platform. The autocannons lacked the firepower to take on heavily defended targets. At close range, though, the combination of lasers poses a significantly bigger threat. The addition of jump jets came late in the design phase, but the Whitworth Jetlift units have proven to be a vital asset over the decades.\xa0The Blackjack's sole significant disadvantage was negative press, which stated that the entire project was a shambles because the 'Mech's basic architecture was defective and unstable.\xa0The 'Mech's tiny footpads were alleged to cause falls and hamper maneuverability, or that the StarGuard II armor was brittle and tended to break off. Despite the fact that none of these accusations were ever proven, the Blackjack went out of favor, and few grieved the loss of GM's production line.", 'Many Blackjacks in the Federated Suns were upgraded to this model during the FedCom Civil War. A half-ton of armor is removed, though the remaining is upgraded to light ferro-fibrous, resulting in almost the same amount of armor protection. All the weapons of the BJ-2 were stripped out and a light fusion engine was added to free up additional mass. Each arm mounts a light autocannon/5 and an ER medium laser, while two tons of CASE-protected ammo in each torso allow the BJ-4 to make use of special munitions. A targeting computer makes all the weapons more accurate.', "The Blackjack had limited use in the Star League, and manufacture was shortly discontinued. Relegated to service with Hegemony planetary militia or sold to League member nations, it can still be encountered on the battlefield today. The majority of them now fight for the Capellan Confederation and the Federated Suns.\xa0The Confederation has nothing but disdain for the design. The breakaway St. Ives Compact, on the other hand, could not be as picky, and the Blackjack serves in the St. Ives Lancers.\xa0The Federated Suns used the Blackjack in the March Militias until the myth of the Blackjack's inferiority was busted on Xhosa VII in 3022. The Crucis Lancers and Deneb Light Cavalry were re-interested in the 'Mech.");