INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (315559, 'Catapult', 'CPLT-C4C', '5453', '65', 'Missile Boat', 'Biped', 'Inner Sphere', '3055', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (315559, 315559, '260 XL Engine(IS)', 'IS Standard', 'Standard', '10 Double', '4', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (315559, 315559, 'Standard(Inner Sphere)', 'LA Armor', '15');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (315559, 315559, 'Standard(Inner Sphere)', 'RA Armor', '15');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (315559, 315559, 'Standard(Inner Sphere)', 'LT Armor', '17');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (315559, 315559, 'Standard(Inner Sphere)', 'RT Armor', '17');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (315559, 315559, 'Standard(Inner Sphere)', 'CT Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (315559, 315559, 'Standard(Inner Sphere)', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (315559, 315559, 'Standard(Inner Sphere)', 'LL Armor', '23');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (315559, 315559, 'Standard(Inner Sphere)', 'RL Armor', '23');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (315559, 315559, 'Standard(Inner Sphere)', 'RTL Armor', '6');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (315559, 315559, 'Standard(Inner Sphere)', 'RTR Armor', '6');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (315559, 315559, 'Standard(Inner Sphere)', 'RTC Armor', '7');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3155591, 315559, 'Small Pulse Laser', 'Center Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3155592, 315559, 'Large Laser', 'Right Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3155593, 315559, 'LRM 20', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3155594, 315559, 'LRM 20', 'Right Arm', NULL);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (3155591, 315559, 'no_arms');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155591, 315559, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155592, 315559, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155593, 315559, 'Left Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155594, 315559, 'Left Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155595, 315559, 'Left Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155596, 315559, 'Left Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155597, 315559, 'Left Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155598, 315559, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155599, 315559, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155600, 315559, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155601, 315559, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155602, 315559, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155603, 315559, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155604, 315559, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155605, 315559, 'Right Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155606, 315559, 'Right Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155607, 315559, 'Right Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155608, 315559, 'Right Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155609, 315559, 'Right Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155610, 315559, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155611, 315559, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155612, 315559, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155613, 315559, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155614, 315559, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155615, 315559, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155616, 315559, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155617, 315559, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155618, 315559, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155619, 315559, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155620, 315559, 'Left Torso', 'BeagleActiveProbe');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155621, 315559, 'Left Torso', 'BeagleActiveProbe');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155622, 315559, 'Left Torso', 'IS Ammo LRM-20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155623, 315559, 'Left Torso', 'IS Ammo LRM-20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155624, 315559, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155625, 315559, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155626, 315559, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155627, 315559, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155628, 315559, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155629, 315559, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155630, 315559, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155631, 315559, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155632, 315559, 'Right Torso', 'Large Laser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155633, 315559, 'Right Torso', 'Large Laser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155634, 315559, 'Right Torso', 'IS Ammo LRM-20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155635, 315559, 'Right Torso', 'IS Ammo LRM-20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155636, 315559, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155637, 315559, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155638, 315559, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155639, 315559, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155640, 315559, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155641, 315559, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155642, 315559, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155643, 315559, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155644, 315559, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155645, 315559, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155646, 315559, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155647, 315559, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155648, 315559, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155649, 315559, 'Center Torso', 'ISSmallPulseLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155650, 315559, 'Center Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155651, 315559, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155652, 315559, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155653, 315559, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155654, 315559, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155655, 315559, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155656, 315559, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155657, 315559, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155658, 315559, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155659, 315559, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155660, 315559, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155661, 315559, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155662, 315559, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155663, 315559, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155664, 315559, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155665, 315559, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155666, 315559, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155667, 315559, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155668, 315559, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155669, 315559, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155670, 315559, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155671, 315559, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155672, 315559, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155673, 315559, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3155674, 315559, 'Left Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (315559, 315559, None, None, None);
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (315559, 315559, None, None, None, None);