INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (740357, 'Catapult', 'CPLT-C3', '481', '65', 'Missile Boat', 'Biped', 'Inner Sphere', '3049', '3', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (740357, 740357, '260 Fusion Engine', 'Standard', 'Standard', '15 Single', '4', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (740357, 740357, 'Standard Armor', 'LA Armor', '13');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (740357, 740357, 'Standard Armor', 'RA Armor', '13');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (740357, 740357, 'Standard Armor', 'LT Armor', '19');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (740357, 740357, 'Standard Armor', 'RT Armor', '19');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (740357, 740357, 'Standard Armor', 'CT Armor', '24');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (740357, 740357, 'Standard Armor', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (740357, 740357, 'Standard Armor', 'LL Armor', '18');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (740357, 740357, 'Standard Armor', 'RL Armor', '18');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (740357, 740357, 'Standard Armor', 'RTL Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (740357, 740357, 'Standard Armor', 'RTR Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (740357, 740357, 'Standard Armor', 'RTC Armor', '11');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7403571, 740357, '1 ISArrowIVSystem', 'Right Arm', 'Ammo:5');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7403572, 740357, '2 ISMediumLaser', 'Center Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7403573, 740357, '1 ISMediumLaser', 'Left Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7403574, 740357, '1 ISMediumLaser', 'Right Torso', None);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (7403571, 740357, 'no_arms');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403571, 740357, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403572, 740357, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403573, 740357, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403574, 740357, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403575, 740357, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403576, 740357, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403577, 740357, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403578, 740357, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403579, 740357, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403580, 740357, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403581, 740357, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403582, 740357, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403583, 740357, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403584, 740357, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403585, 740357, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403586, 740357, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403587, 740357, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403588, 740357, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403589, 740357, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403590, 740357, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403591, 740357, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403592, 740357, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403593, 740357, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403594, 740357, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403595, 740357, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403596, 740357, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403597, 740357, 'Left Torso', 'ISMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403598, 740357, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403599, 740357, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403600, 740357, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403601, 740357, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403602, 740357, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403603, 740357, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403604, 740357, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403605, 740357, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403606, 740357, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403607, 740357, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403608, 740357, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403609, 740357, 'Right Torso', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403610, 740357, 'Right Torso', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403611, 740357, 'Right Torso', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403612, 740357, 'Right Torso', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403613, 740357, 'Right Torso', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403614, 740357, 'Right Torso', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403615, 740357, 'Right Torso', 'ISMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403616, 740357, 'Right Torso', 'ISArrowIV Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403617, 740357, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403618, 740357, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403619, 740357, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403620, 740357, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403621, 740357, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403622, 740357, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403623, 740357, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403624, 740357, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403625, 740357, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403626, 740357, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403627, 740357, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403628, 740357, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403629, 740357, 'Center Torso', 'ISMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403630, 740357, 'Center Torso', 'ISMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403631, 740357, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403632, 740357, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403633, 740357, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403634, 740357, 'Head', 'Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403635, 740357, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403636, 740357, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403637, 740357, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403638, 740357, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403639, 740357, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403640, 740357, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403641, 740357, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403642, 740357, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403643, 740357, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403644, 740357, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403645, 740357, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403646, 740357, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403647, 740357, 'Left Leg', 'Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403648, 740357, 'Left Leg', 'Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403649, 740357, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403650, 740357, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403651, 740357, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403652, 740357, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403653, 740357, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7403654, 740357, 'Left Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (740357, 740357, None, None, None);
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (740357, 740357, None, None, None, None);