INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (300036, 'Catapult', 'CPLT-K5', '489', '65', 'Skirmisher', 'Biped', 'Inner Sphere', '3058', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (300036, 300036, '260 XL Fusion Engine', 'Endo-Steel', 'Standard', '12 Double', '4', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300036, 300036, 'Standard Armor', 'LA Armor', '20');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300036, 300036, 'Standard Armor', 'RA Armor', '20');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300036, 300036, 'Standard Armor', 'LT Armor', '21');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300036, 300036, 'Standard Armor', 'RT Armor', '21');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300036, 300036, 'Standard Armor', 'CT Armor', '30');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300036, 300036, 'Standard Armor', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300036, 300036, 'Standard Armor', 'LL Armor', '25');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300036, 300036, 'Standard Armor', 'RL Armor', '25');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300036, 300036, 'Standard Armor', 'RTL Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300036, 300036, 'Standard Armor', 'RTR Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300036, 300036, 'Standard Armor', 'RTC Armor', '11');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3000361, 300036, '1 ISMediumPulseLaser', 'Center Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3000362, 300036, '1 ISMediumPulseLaser', 'Center Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3000363, 300036, '1 ISC3SlaveUnit', 'Head', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3000364, 300036, '1 ISMRM30', 'Right Arm', Ammo:32);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3000365, 300036, '1 ISMRM30', 'Left Arm', NULL);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (3000361, 300036, 'no_arms');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000361, 300036, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000362, 300036, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000363, 300036, 'Left Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000364, 300036, 'Left Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000365, 300036, 'Left Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000366, 300036, 'Left Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000367, 300036, 'Left Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000368, 300036, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000369, 300036, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000370, 300036, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000371, 300036, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000372, 300036, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000373, 300036, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000374, 300036, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000375, 300036, 'Right Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000376, 300036, 'Right Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000377, 300036, 'Right Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000378, 300036, 'Right Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000379, 300036, 'Right Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000380, 300036, 'Right Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000381, 300036, 'Right Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000382, 300036, 'Right Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000383, 300036, 'Right Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000384, 300036, 'Right Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000385, 300036, 'Left Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000386, 300036, 'Left Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000387, 300036, 'Left Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000388, 300036, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000389, 300036, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000390, 300036, 'Left Torso', 'ISMRM30 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000391, 300036, 'Left Torso', 'ISMRM30 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000392, 300036, 'Left Torso', 'ISCASE');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000393, 300036, 'Left Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000394, 300036, 'Left Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000395, 300036, 'Left Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000396, 300036, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000397, 300036, 'Right Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000398, 300036, 'Right Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000399, 300036, 'Right Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000400, 300036, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000401, 300036, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000402, 300036, 'Right Torso', 'ISMRM30 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000403, 300036, 'Right Torso', 'ISMRM30 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000404, 300036, 'Right Torso', 'ISCASE');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000405, 300036, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000406, 300036, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000407, 300036, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000408, 300036, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000409, 300036, 'Center Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000410, 300036, 'Center Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000411, 300036, 'Center Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000412, 300036, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000413, 300036, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000414, 300036, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000415, 300036, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000416, 300036, 'Center Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000417, 300036, 'Center Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000418, 300036, 'Center Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000419, 300036, 'Center Torso', 'ISMediumPulseLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000420, 300036, 'Center Torso', 'ISMediumPulseLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000421, 300036, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000422, 300036, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000423, 300036, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000424, 300036, 'Head', 'ISC3SlaveUnit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000425, 300036, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000426, 300036, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000427, 300036, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000428, 300036, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000429, 300036, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000430, 300036, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000431, 300036, 'Left Leg', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000432, 300036, 'Left Leg', 'Endo-Steel');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (300036, 300036, None, None, None);
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (300036, 300036, None, None, None, None);