INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (296899, 'Catapult', 'CPLT-C4C', '5453', '65', 'Missile Boat', 'Biped', 'Inner Sphere', '3055', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (296899, 296899, '260 XL Engine(IS)', 'IS Standard', 'Standard', '10 Double', '4', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (296899, 296899, 'Standard(Inner Sphere)', 'LA Armor', '15');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (296899, 296899, 'Standard(Inner Sphere)', 'RA Armor', '15');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (296899, 296899, 'Standard(Inner Sphere)', 'LT Armor', '17');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (296899, 296899, 'Standard(Inner Sphere)', 'RT Armor', '17');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (296899, 296899, 'Standard(Inner Sphere)', 'CT Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (296899, 296899, 'Standard(Inner Sphere)', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (296899, 296899, 'Standard(Inner Sphere)', 'LL Armor', '23');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (296899, 296899, 'Standard(Inner Sphere)', 'RL Armor', '23');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (296899, 296899, 'Standard(Inner Sphere)', 'RTL Armor', '6');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (296899, 296899, 'Standard(Inner Sphere)', 'RTR Armor', '6');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (296899, 296899, 'Standard(Inner Sphere)', 'RTC Armor', '7');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2968991, 296899, 'Small Pulse Laser', 'Center Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2968992, 296899, 'Large Laser', 'Right Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2968993, 296899, 'LRM 20', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2968994, 296899, 'LRM 20', 'Right Arm', None);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (2968991, 296899, 'no_arms');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2968991, 296899, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2968992, 296899, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2968993, 296899, 'Left Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2968994, 296899, 'Left Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2968995, 296899, 'Left Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2968996, 296899, 'Left Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2968997, 296899, 'Left Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2968998, 296899, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2968999, 296899, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969000, 296899, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969001, 296899, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969002, 296899, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969003, 296899, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969004, 296899, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969005, 296899, 'Right Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969006, 296899, 'Right Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969007, 296899, 'Right Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969008, 296899, 'Right Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969009, 296899, 'Right Arm', 'LRM 20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969010, 296899, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969011, 296899, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969012, 296899, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969013, 296899, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969014, 296899, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969015, 296899, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969016, 296899, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969017, 296899, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969018, 296899, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969019, 296899, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969020, 296899, 'Left Torso', 'BeagleActiveProbe');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969021, 296899, 'Left Torso', 'BeagleActiveProbe');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969022, 296899, 'Left Torso', 'IS Ammo LRM-20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969023, 296899, 'Left Torso', 'IS Ammo LRM-20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969024, 296899, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969025, 296899, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969026, 296899, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969027, 296899, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969028, 296899, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969029, 296899, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969030, 296899, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969031, 296899, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969032, 296899, 'Right Torso', 'Large Laser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969033, 296899, 'Right Torso', 'Large Laser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969034, 296899, 'Right Torso', 'IS Ammo LRM-20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969035, 296899, 'Right Torso', 'IS Ammo LRM-20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969036, 296899, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969037, 296899, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969038, 296899, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969039, 296899, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969040, 296899, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969041, 296899, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969042, 296899, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969043, 296899, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969044, 296899, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969045, 296899, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969046, 296899, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969047, 296899, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969048, 296899, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969049, 296899, 'Center Torso', 'ISSmallPulseLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969050, 296899, 'Center Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969051, 296899, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969052, 296899, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969053, 296899, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969054, 296899, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969055, 296899, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969056, 296899, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969057, 296899, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969058, 296899, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969059, 296899, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969060, 296899, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969061, 296899, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969062, 296899, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969063, 296899, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969064, 296899, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969065, 296899, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969066, 296899, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969067, 296899, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969068, 296899, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969069, 296899, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969070, 296899, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969071, 296899, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969072, 296899, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969073, 296899, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2969074, 296899, 'Left Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (296899, 296899, None, None, None);
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (296899, 296899, None, None, None, None);