INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (317775, 'Catapult', 'CPLT-H2', '486', '65', 'Skirmisher', 'Biped', 'Inner Sphere', '3064', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (317775, 317775, '260 Fusion Engine', 'Standard', 'Standard', '13 Double', '4', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (317775, 317775, 'Standard Armor', 'LA Armor', '13');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (317775, 317775, 'Standard Armor', 'RA Armor', '13');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (317775, 317775, 'Standard Armor', 'LT Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (317775, 317775, 'Standard Armor', 'RT Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (317775, 317775, 'Standard Armor', 'CT Armor', '26');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (317775, 317775, 'Standard Armor', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (317775, 317775, 'Standard Armor', 'LL Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (317775, 317775, 'Standard Armor', 'RL Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (317775, 317775, 'Standard Armor', 'RTL Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (317775, 317775, 'Standard Armor', 'RTR Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (317775, 317775, 'Standard Armor', 'RTC Armor', '11');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3177751, 317775, '3 ISRocketLauncher20', 'Right Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3177752, 317775, '1 ISPPC', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3177753, 317775, '1 ISRocketLauncher20', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3177754, 317775, '2 ISRocketLauncher20', 'Right Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3177755, 317775, '2 ISRocketLauncher20', 'Left Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3177756, 317775, '2 ISMediumLaser', 'Center Torso', None);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (3177751, 317775, 'no_arms');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177751, 317775, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177752, 317775, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177753, 317775, 'Left Arm', 'ISPPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177754, 317775, 'Left Arm', 'ISPPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177755, 317775, 'Left Arm', 'ISPPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177756, 317775, 'Left Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177757, 317775, 'Left Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177758, 317775, 'Left Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177759, 317775, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177760, 317775, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177761, 317775, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177762, 317775, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177763, 317775, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177764, 317775, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177765, 317775, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177766, 317775, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177767, 317775, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177768, 317775, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177769, 317775, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177770, 317775, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177771, 317775, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177772, 317775, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177773, 317775, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177774, 317775, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177775, 317775, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177776, 317775, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177777, 317775, 'Left Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177778, 317775, 'Left Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177779, 317775, 'Left Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177780, 317775, 'Left Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177781, 317775, 'Left Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177782, 317775, 'Left Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177783, 317775, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177784, 317775, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177785, 317775, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177786, 317775, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177787, 317775, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177788, 317775, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177789, 317775, 'Right Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177790, 317775, 'Right Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177791, 317775, 'Right Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177792, 317775, 'Right Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177793, 317775, 'Right Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177794, 317775, 'Right Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177795, 317775, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177796, 317775, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177797, 317775, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177798, 317775, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177799, 317775, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177800, 317775, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177801, 317775, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177802, 317775, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177803, 317775, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177804, 317775, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177805, 317775, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177806, 317775, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177807, 317775, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177808, 317775, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177809, 317775, 'Center Torso', 'ISMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177810, 317775, 'Center Torso', 'ISMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177811, 317775, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177812, 317775, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177813, 317775, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177814, 317775, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177815, 317775, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177816, 317775, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177817, 317775, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177818, 317775, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177819, 317775, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177820, 317775, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177821, 317775, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177822, 317775, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177823, 317775, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177824, 317775, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177825, 317775, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177826, 317775, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177827, 317775, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177828, 317775, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177829, 317775, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177830, 317775, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177831, 317775, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177832, 317775, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177833, 317775, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3177834, 317775, 'Left Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (317775, 317775, None, None, None);
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (317775, 317775, None, None, None, None);