INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (406342, 'Catapult', 'CPLT-C5', '483', '65', 'Missile Boat', 'Biped', 'Inner Sphere', '3061', '3', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (406342, 406342, '260 Fusion Engine', 'Endo Steel', 'Standard', '12 Double', '4', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (406342, 406342, 'Standard Armor', 'LA Armor', '20');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (406342, 406342, 'Standard Armor', 'RA Armor', '20');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (406342, 406342, 'Standard Armor', 'LT Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (406342, 406342, 'Standard Armor', 'RT Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (406342, 406342, 'Standard Armor', 'CT Armor', '28');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (406342, 406342, 'Standard Armor', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (406342, 406342, 'Standard Armor', 'LL Armor', '26');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (406342, 406342, 'Standard Armor', 'RL Armor', '26');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (406342, 406342, 'Standard Armor', 'RTL Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (406342, 406342, 'Standard Armor', 'RTR Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (406342, 406342, 'Standard Armor', 'RTC Armor', '11');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (4063421, 406342, '1 ISArrowIVSystem', 'Right Arm', 'Ammo:20');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (4063422, 406342, '1 ISERMediumLaser', 'Right Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (4063423, 406342, '2 ISERMediumLaser', 'Center Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (4063424, 406342, '1 ISERMediumLaser', 'Left Torso', None);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (4063421, 406342, 'no_arms');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063421, 406342, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063422, 406342, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063423, 406342, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063424, 406342, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063425, 406342, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063426, 406342, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063427, 406342, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063428, 406342, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063429, 406342, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063430, 406342, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063431, 406342, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063432, 406342, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063433, 406342, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063434, 406342, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063435, 406342, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063436, 406342, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063437, 406342, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063438, 406342, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063439, 406342, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063440, 406342, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063441, 406342, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063442, 406342, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063443, 406342, 'Right Arm', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063444, 406342, 'Right Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063445, 406342, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063446, 406342, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063447, 406342, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063448, 406342, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063449, 406342, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063450, 406342, 'Left Torso', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063451, 406342, 'Left Torso', 'ISArrowIV Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063452, 406342, 'Left Torso', 'ISArrowIV Homing Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063453, 406342, 'Left Torso', 'ISArrowIV Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063454, 406342, 'Left Torso', 'ISArrowIV Homing Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063455, 406342, 'Left Torso', 'ISCASE');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063456, 406342, 'Left Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063457, 406342, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063458, 406342, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063459, 406342, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063460, 406342, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063461, 406342, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063462, 406342, 'Right Torso', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063463, 406342, 'Right Torso', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063464, 406342, 'Right Torso', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063465, 406342, 'Right Torso', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063466, 406342, 'Right Torso', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063467, 406342, 'Right Torso', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063468, 406342, 'Right Torso', 'ISArrowIVSystem (Split)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063469, 406342, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063470, 406342, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063471, 406342, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063472, 406342, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063473, 406342, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063474, 406342, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063475, 406342, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063476, 406342, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063477, 406342, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063478, 406342, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063479, 406342, 'Center Torso', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063480, 406342, 'Center Torso', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063481, 406342, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063482, 406342, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063483, 406342, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063484, 406342, 'Head', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063485, 406342, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063486, 406342, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063487, 406342, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063488, 406342, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063489, 406342, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063490, 406342, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063491, 406342, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063492, 406342, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063493, 406342, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063494, 406342, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063495, 406342, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063496, 406342, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063497, 406342, 'Left Leg', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063498, 406342, 'Left Leg', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063499, 406342, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063500, 406342, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063501, 406342, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063502, 406342, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063503, 406342, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4063504, 406342, 'Left Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (406342, 406342, None, None, None);
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (406342, 406342, None, None, None, None);