INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (636588, 'Catapult', 'CPLT-C6', '485', '65', 'Skirmisher', 'Biped', 'Inner Sphere', '3069', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (636588, 636588, '260 Fusion Engine', 'Endo Steel', 'Standard', '15 Double', '4', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (636588, 636588, 'Standard', 'LA Armor', '20');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (636588, 636588, 'Standard', 'RA Armor', '20');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (636588, 636588, 'Standard', 'LT Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (636588, 636588, 'Standard', 'RT Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (636588, 636588, 'Standard', 'CT Armor', '28');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (636588, 636588, 'Standard', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (636588, 636588, 'Standard', 'LL Armor', '26');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (636588, 636588, 'Standard', 'RL Armor', '26');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (636588, 636588, 'Standard', 'RTL Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (636588, 636588, 'Standard', 'RTR Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (636588, 636588, 'Standard', 'RTC Armor', '11');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (6365881, 636588, '2 ISPlasmaRifle', 'Right Arm', Ammo:60);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (6365882, 636588, '2 ISERMediumLaser', 'Center Torso', NULL);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (6365881, 636588, 'no_arms');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365881, 636588, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365882, 636588, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365883, 636588, 'Left Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365884, 636588, 'Left Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365885, 636588, 'Left Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365886, 636588, 'Left Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365887, 636588, 'Left Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365888, 636588, 'Left Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365889, 636588, 'Left Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365890, 636588, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365891, 636588, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365892, 636588, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365893, 636588, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365894, 636588, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365895, 636588, 'Right Arm', 'ISPlasmaRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365896, 636588, 'Right Arm', 'ISPlasmaRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365897, 636588, 'Right Arm', 'ISPlasmaRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365898, 636588, 'Right Arm', 'ISPlasmaRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365899, 636588, 'Right Arm', 'ISPlasmaRifle Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365900, 636588, 'Right Arm', 'ISPlasmaRifle Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365901, 636588, 'Right Arm', 'ISPlasmaRifle Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365902, 636588, 'Right Arm', 'ISPlasmaRifle Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365903, 636588, 'Right Arm', 'ISPlasmaRifle Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365904, 636588, 'Right Arm', 'ISPlasmaRifle Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365905, 636588, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365906, 636588, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365907, 636588, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365908, 636588, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365909, 636588, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365910, 636588, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365911, 636588, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365912, 636588, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365913, 636588, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365914, 636588, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365915, 636588, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365916, 636588, 'Left Torso', 'ISCASE');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365917, 636588, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365918, 636588, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365919, 636588, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365920, 636588, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365921, 636588, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365922, 636588, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365923, 636588, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365924, 636588, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365925, 636588, 'Right Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365926, 636588, 'Right Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365927, 636588, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365928, 636588, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365929, 636588, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365930, 636588, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365931, 636588, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365932, 636588, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365933, 636588, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365934, 636588, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365935, 636588, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365936, 636588, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365937, 636588, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365938, 636588, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365939, 636588, 'Center Torso', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365940, 636588, 'Center Torso', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365941, 636588, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365942, 636588, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365943, 636588, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365944, 636588, 'Head', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365945, 636588, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365946, 636588, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365947, 636588, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365948, 636588, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365949, 636588, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365950, 636588, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365951, 636588, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365952, 636588, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365953, 636588, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365954, 636588, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365955, 636588, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365956, 636588, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365957, 636588, 'Left Leg', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365958, 636588, 'Left Leg', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365959, 636588, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365960, 636588, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365961, 636588, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365962, 636588, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365963, 636588, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6365964, 636588, 'Left Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (636588, 636588, None, None, None);
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (636588, 636588, None, None, None, None);