INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (121867, 'Catapult', 'CPLT-H2', '486', '65', 'Skirmisher', 'Biped', 'Inner Sphere', '3064', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (121867, 121867, '260 Fusion Engine', 'Standard', 'Standard', '13 Double', '4', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (121867, 121867, 'Standard Armor', 'LA Armor', '13');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (121867, 121867, 'Standard Armor', 'RA Armor', '13');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (121867, 121867, 'Standard Armor', 'LT Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (121867, 121867, 'Standard Armor', 'RT Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (121867, 121867, 'Standard Armor', 'CT Armor', '26');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (121867, 121867, 'Standard Armor', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (121867, 121867, 'Standard Armor', 'LL Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (121867, 121867, 'Standard Armor', 'RL Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (121867, 121867, 'Standard Armor', 'RTL Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (121867, 121867, 'Standard Armor', 'RTR Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (121867, 121867, 'Standard Armor', 'RTC Armor', '11');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1218671, 121867, '3 ISRocketLauncher20', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1218672, 121867, '1 ISPPC', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1218673, 121867, '1 ISRocketLauncher20', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1218674, 121867, '2 ISRocketLauncher20', 'Right Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1218675, 121867, '2 ISRocketLauncher20', 'Left Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1218676, 121867, '2 ISMediumLaser', 'Center Torso', NULL);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (1218671, 121867, 'no_arms');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218671, 121867, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218672, 121867, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218673, 121867, 'Left Arm', 'ISPPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218674, 121867, 'Left Arm', 'ISPPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218675, 121867, 'Left Arm', 'ISPPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218676, 121867, 'Left Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218677, 121867, 'Left Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218678, 121867, 'Left Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218679, 121867, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218680, 121867, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218681, 121867, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218682, 121867, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218683, 121867, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218684, 121867, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218685, 121867, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218686, 121867, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218687, 121867, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218688, 121867, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218689, 121867, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218690, 121867, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218691, 121867, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218692, 121867, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218693, 121867, 'Right Arm', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218694, 121867, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218695, 121867, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218696, 121867, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218697, 121867, 'Left Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218698, 121867, 'Left Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218699, 121867, 'Left Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218700, 121867, 'Left Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218701, 121867, 'Left Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218702, 121867, 'Left Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218703, 121867, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218704, 121867, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218705, 121867, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218706, 121867, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218707, 121867, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218708, 121867, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218709, 121867, 'Right Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218710, 121867, 'Right Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218711, 121867, 'Right Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218712, 121867, 'Right Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218713, 121867, 'Right Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218714, 121867, 'Right Torso', 'ISRocketLauncher20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218715, 121867, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218716, 121867, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218717, 121867, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218718, 121867, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218719, 121867, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218720, 121867, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218721, 121867, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218722, 121867, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218723, 121867, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218724, 121867, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218725, 121867, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218726, 121867, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218727, 121867, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218728, 121867, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218729, 121867, 'Center Torso', 'ISMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218730, 121867, 'Center Torso', 'ISMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218731, 121867, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218732, 121867, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218733, 121867, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218734, 121867, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218735, 121867, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218736, 121867, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218737, 121867, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218738, 121867, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218739, 121867, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218740, 121867, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218741, 121867, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218742, 121867, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218743, 121867, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218744, 121867, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218745, 121867, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218746, 121867, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218747, 121867, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218748, 121867, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218749, 121867, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218750, 121867, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218751, 121867, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218752, 121867, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218753, 121867, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1218754, 121867, 'Left Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (121867, 121867, None, None, None);
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (121867, 121867, None, None, None, None);