INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (305949, 'Catapult', 'CPLT-K5', '489', '65', 'Skirmisher', 'Biped', 'Inner Sphere', '3058', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (305949, 305949, '260 XL Fusion Engine', 'Endo-Steel', 'Standard', '12 Double', '4', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (305949, 305949, 'Standard Armor', 'LA Armor', '20');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (305949, 305949, 'Standard Armor', 'RA Armor', '20');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (305949, 305949, 'Standard Armor', 'LT Armor', '21');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (305949, 305949, 'Standard Armor', 'RT Armor', '21');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (305949, 305949, 'Standard Armor', 'CT Armor', '30');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (305949, 305949, 'Standard Armor', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (305949, 305949, 'Standard Armor', 'LL Armor', '25');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (305949, 305949, 'Standard Armor', 'RL Armor', '25');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (305949, 305949, 'Standard Armor', 'RTL Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (305949, 305949, 'Standard Armor', 'RTR Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (305949, 305949, 'Standard Armor', 'RTC Armor', '11');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3059491, 305949, '1 ISMediumPulseLaser', 'Center Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3059492, 305949, '1 ISMediumPulseLaser', 'Center Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3059493, 305949, '1 ISC3SlaveUnit', 'Head', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3059494, 305949, '1 ISMRM30', 'Right Arm', 'Ammo:32');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3059495, 305949, '1 ISMRM30', 'Left Arm', None);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (3059491, 305949, 'no_arms');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059491, 305949, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059492, 305949, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059493, 305949, 'Left Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059494, 305949, 'Left Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059495, 305949, 'Left Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059496, 305949, 'Left Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059497, 305949, 'Left Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059498, 305949, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059499, 305949, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059500, 305949, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059501, 305949, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059502, 305949, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059503, 305949, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059504, 305949, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059505, 305949, 'Right Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059506, 305949, 'Right Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059507, 305949, 'Right Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059508, 305949, 'Right Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059509, 305949, 'Right Arm', 'ISMRM30');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059510, 305949, 'Right Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059511, 305949, 'Right Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059512, 305949, 'Right Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059513, 305949, 'Right Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059514, 305949, 'Right Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059515, 305949, 'Left Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059516, 305949, 'Left Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059517, 305949, 'Left Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059518, 305949, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059519, 305949, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059520, 305949, 'Left Torso', 'ISMRM30 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059521, 305949, 'Left Torso', 'ISMRM30 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059522, 305949, 'Left Torso', 'ISCASE');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059523, 305949, 'Left Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059524, 305949, 'Left Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059525, 305949, 'Left Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059526, 305949, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059527, 305949, 'Right Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059528, 305949, 'Right Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059529, 305949, 'Right Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059530, 305949, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059531, 305949, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059532, 305949, 'Right Torso', 'ISMRM30 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059533, 305949, 'Right Torso', 'ISMRM30 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059534, 305949, 'Right Torso', 'ISCASE');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059535, 305949, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059536, 305949, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059537, 305949, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059538, 305949, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059539, 305949, 'Center Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059540, 305949, 'Center Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059541, 305949, 'Center Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059542, 305949, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059543, 305949, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059544, 305949, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059545, 305949, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059546, 305949, 'Center Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059547, 305949, 'Center Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059548, 305949, 'Center Torso', 'Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059549, 305949, 'Center Torso', 'ISMediumPulseLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059550, 305949, 'Center Torso', 'ISMediumPulseLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059551, 305949, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059552, 305949, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059553, 305949, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059554, 305949, 'Head', 'ISC3SlaveUnit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059555, 305949, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059556, 305949, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059557, 305949, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059558, 305949, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059559, 305949, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059560, 305949, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059561, 305949, 'Left Leg', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3059562, 305949, 'Left Leg', 'Endo-Steel');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (305949, 305949, None, None, None);
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (305949, 305949, None, None, None, None);