INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (338885, 'Cicada', 'CDA-3F', '594', '40', 'Striker', 'Biped', 'Inner Sphere', '3052', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (338885, 338885, '320 XL Engine', 'Endo Steel', 'Standard', '10 Double', '8', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (338885, 338885, 'Ferro-Fibrous', 'LA Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (338885, 338885, 'Ferro-Fibrous', 'RA Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (338885, 338885, 'Ferro-Fibrous', 'LT Armor', '15');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (338885, 338885, 'Ferro-Fibrous', 'RT Armor', '15');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (338885, 338885, 'Ferro-Fibrous', 'CT Armor', '15');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (338885, 338885, 'Ferro-Fibrous', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (338885, 338885, 'Ferro-Fibrous', 'LL Armor', '15');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (338885, 338885, 'Ferro-Fibrous', 'RL Armor', '15');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (338885, 338885, 'Ferro-Fibrous', 'RTL Armor', '5');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (338885, 338885, 'Ferro-Fibrous', 'RTR Armor', '5');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (338885, 338885, 'Ferro-Fibrous', 'RTC Armor', '6');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3388851, 338885, '1 ISMediumLaser', 'Right Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3388852, 338885, '1 ISMediumLaser', 'Left Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3388853, 338885, '1 ISERPPC', 'Left Torso', NULL);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (3388851, 338885, 'no_arms');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388851, 338885, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388852, 338885, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388853, 338885, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388854, 338885, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388855, 338885, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388856, 338885, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388857, 338885, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388858, 338885, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388859, 338885, 'Left Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388860, 338885, 'Left Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388861, 338885, 'Left Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388862, 338885, 'Left Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388863, 338885, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388864, 338885, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388865, 338885, 'Right Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388866, 338885, 'Right Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388867, 338885, 'Right Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388868, 338885, 'Right Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388869, 338885, 'Right Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388870, 338885, 'Right Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388871, 338885, 'Right Arm', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388872, 338885, 'Right Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388873, 338885, 'Right Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388874, 338885, 'Right Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388875, 338885, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388876, 338885, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388877, 338885, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388878, 338885, 'Left Torso', 'ISMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388879, 338885, 'Left Torso', 'ISERPPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388880, 338885, 'Left Torso', 'ISERPPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388881, 338885, 'Left Torso', 'ISERPPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388882, 338885, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388883, 338885, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388884, 338885, 'Left Torso', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388885, 338885, 'Left Torso', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388886, 338885, 'Left Torso', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388887, 338885, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388888, 338885, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388889, 338885, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388890, 338885, 'Right Torso', 'ISMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388891, 338885, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388892, 338885, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388893, 338885, 'Right Torso', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388894, 338885, 'Right Torso', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388895, 338885, 'Right Torso', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388896, 338885, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388897, 338885, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388898, 338885, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388899, 338885, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388900, 338885, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388901, 338885, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388902, 338885, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388903, 338885, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388904, 338885, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388905, 338885, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388906, 338885, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388907, 338885, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388908, 338885, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388909, 338885, 'Center Torso', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388910, 338885, 'Center Torso', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388911, 338885, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388912, 338885, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388913, 338885, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388914, 338885, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388915, 338885, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388916, 338885, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388917, 338885, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388918, 338885, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388919, 338885, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388920, 338885, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388921, 338885, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388922, 338885, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388923, 338885, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388924, 338885, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388925, 338885, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388926, 338885, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388927, 338885, 'Left Leg', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388928, 338885, 'Left Leg', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388929, 338885, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388930, 338885, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388931, 338885, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388932, 338885, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388933, 338885, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388934, 338885, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388935, 338885, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388936, 338885, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388937, 338885, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388938, 338885, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388939, 338885, 'Right Leg', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388940, 338885, 'Right Leg', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388941, 338885, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388942, 338885, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388943, 338885, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388944, 338885, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388945, 338885, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3388946, 338885, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (338885, 338885, 'Gibson Federated BattleMechs (A Division of Free Worlds Defense Industries)', 'Gibson', 'CHASSIS:Kell Reinforced 240');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (338885, 338885, 'Designed as a supplement or replacement for the popular Locust scout ’Mech, the Cicada found limited use by the Star League after its introduction in 2740.', "The Cicada''s main advantages are its speed and a lack of ammunition. A gigantic Pitban 320 engine, which accounts for more than half of the Cicada''s entire mass, propels the 40-ton BattleMech to almost 130 kph. A trio of lasers, two medium and one small, provide the Cicada with ample firepower to take on its chosen targets: lighter ''Mechs. The lasers are implanted in the Cicada''s armored midsection, beneath the toughest shielding the ''Mech mounts, however their shooting arcs are limited. A foe who is successful in getting behind the Cicada has little to fear. The rest of the ''Mech, however, is just minimally armored. Its limbs are vestigial—really, wings—and can only carry little armor. The Cicada''s legs, while robust enough to carry the ''Mech at breakneck speeds, are also unarmored.", "The -3F Cicada is one of the most advanced versions of this ''Mech, with upgrades based on combat reports from the front lines of the Clan Invasion, and was introduced in 3052. The chassis has been constructed using endo steel and is protected with six and a half tons of ferro-fibrous armor. The -3F is powered by an extralight engine and carries a weapons loadout that appears to be a cross between the 2A and 3C models, with the primary weapon being an ER PPC, backed up by two medium lasers. What''s more, the Cicada can now jump up to 240 meters thanks to the inclusion of eight jump jets.", "The Cicada was introduced amidst rising tensions in 2740 by HartfordCo Industries in an attempt to capitalize on the growing need for BattleMechs. At the time Bergan Industries had cornered the market in light recon ''Mechs with their Locust and HartfordCo''s only prior experience was building communications and targeting systems. Nevertheless the company designed their ''Mech to compete directly with the Locust by making it just as fast but twice as large, allowing the Cicada to carry slightly better weaponry and give it an edge in physical combat, all while keeping costs down. The Star League was sufficiently impressed that they agreed to a limited contract with HartfordCo for a small number of Cicadas, using them to replace many Locusts lost in fighting along its border regions. The ''Mech''s only major issue was faulty heat sinks, although these were eventually replaced in many models with modular sinks. With their base of operations and only Cicada factory located on Bryant, HartfordCo was among the many victims of the fall of the Star League and the onset of the Succession Wars. Although the factory was destroyed, there were a number of built Cicadas in storage on Bryant and its relative position compared to the five Successor States meant the planet was the target of many raids. Thus the Cicada found its way into all of the major House armies, where in service to the Successor Lords, the ''Mech earned a positive reputation. Unfortunately this also meant its expectations sometimes exceeded the design''s actual capabilities, and, with no new models being produced, the Cicada''s numbers began to dwindle. By the end of the Fourth Succession War the ''Mech was in danger of going extinct. The discovery of the Helm Memory Core allowed Free Worlds Defense Industries to save the Cicada by restarting production of the ''Mech from their newly-refurbished production line on Gibson. The great majority of these newly-built Cicadas went to the Free Worlds League Military, particularly federal units, which were in desperate need for recon ''Mechs after the loss of so many machines during their long battle with Andurien. The chassis was also the perfect platform to apply much of the now-recovered lostech and the improved CDA-3M was introduced shortly before the start of the Clan Invasion. New Cicadas were supplied to the Federated Commonwealth and Draconis Combine as part of an agreement to combat the Clans, and as reports filtered in from the front more variants of the ''Mech were produced. Following the ComStar Schism the Word of Blake relocated to Gibson and an increasing amount of Cicada production was redirected to the Word of Blake Militia, which quickly rivaled the FWLM as the largest Cicada user. As such the ''Mech was found on both sides of the Jihad.");