INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (224587, 'Commando', 'COM-7S', '676', '25', 'Striker', 'Biped', 'Inner Sphere', '3060', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (224587, 224587, '150 Light Engine', 'Endo Steel', 'Standard', '10 Double', '6', '0');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (224587, 224587, 'Standard Armor', 'LA Armor', '5');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (224587, 224587, 'Standard Armor', 'RA Armor', '5');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (224587, 224587, 'Standard Armor', 'LT Armor', '7');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (224587, 224587, 'Standard Armor', 'RT Armor', '7');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (224587, 224587, 'Standard Armor', 'CT Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (224587, 224587, 'Standard Armor', 'HD Armor', '5');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (224587, 224587, 'Standard Armor', 'LL Armor', '6');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (224587, 224587, 'Standard Armor', 'RL Armor', '6');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (224587, 224587, 'Standard Armor', 'RTL Armor', '2');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (224587, 224587, 'Standard Armor', 'RTR Armor', '2');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (224587, 224587, 'Standard Armor', 'RTC Armor', '3');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2245871, 224587, '2 ISStreakSRM2', 'Right Arm', Ammo:50);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2245872, 224587, '2 ISERMediumLaser', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2245873, 224587, '1 ISSRM4', 'Center Torso', Ammo:25);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (2245871, 224587, 'low_profile');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245871, 224587, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245872, 224587, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245873, 224587, 'Left Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245874, 224587, 'Left Arm', 'Hand Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245875, 224587, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245876, 224587, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245877, 224587, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245878, 224587, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245879, 224587, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245880, 224587, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245881, 224587, 'Left Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245882, 224587, 'Left Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245883, 224587, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245884, 224587, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245885, 224587, 'Right Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245886, 224587, 'Right Arm', 'Hand Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245887, 224587, 'Right Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245888, 224587, 'Right Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245889, 224587, 'Right Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245890, 224587, 'Right Arm', 'ISStreakSRM2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245891, 224587, 'Right Arm', 'ISStreakSRM2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245892, 224587, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245893, 224587, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245894, 224587, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245895, 224587, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245896, 224587, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245897, 224587, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245898, 224587, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245899, 224587, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245900, 224587, 'Left Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245901, 224587, 'Left Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245902, 224587, 'Left Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245903, 224587, 'Left Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245904, 224587, 'Left Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245905, 224587, 'Left Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245906, 224587, 'Left Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245907, 224587, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245908, 224587, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245909, 224587, 'Right Torso', 'ISSRM4 Ammo Artemis-capable');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245910, 224587, 'Right Torso', 'ISStreakSRM2 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245911, 224587, 'Right Torso', 'ISCASE');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245912, 224587, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245913, 224587, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245914, 224587, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245915, 224587, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245916, 224587, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245917, 224587, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245918, 224587, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245919, 224587, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245920, 224587, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245921, 224587, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245922, 224587, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245923, 224587, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245924, 224587, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245925, 224587, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245926, 224587, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245927, 224587, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245928, 224587, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245929, 224587, 'Center Torso', 'ISSRM4');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245930, 224587, 'Center Torso', 'ISArtemisIV');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245931, 224587, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245932, 224587, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245933, 224587, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245934, 224587, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245935, 224587, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245936, 224587, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245937, 224587, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245938, 224587, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245939, 224587, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245940, 224587, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245941, 224587, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245942, 224587, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245943, 224587, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245944, 224587, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245945, 224587, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245946, 224587, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245947, 224587, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245948, 224587, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245949, 224587, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245950, 224587, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245951, 224587, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245952, 224587, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245953, 224587, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245954, 224587, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245955, 224587, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245956, 224587, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245957, 224587, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245958, 224587, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245959, 224587, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245960, 224587, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245961, 224587, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245962, 224587, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245963, 224587, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245964, 224587, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245965, 224587, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2245966, 224587, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (224587, 224587, 'Coventry Metal Works', 'Coventry', 'CHASSIS:Foundation Ultralight Endo Steel');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (224587, 224587, "Created for the Lyran Commonwealth Armed Forces and one of the first ''Mechs ever designed for reconnaissance, the Commando was much lighter and faster than its precursors, though it still utilized primitive BattleMech technology.", 'With only four tons of armor to protect itself, the Commando is not meant to participate in a stand-up fight against heavier enemies, but it excels at hit-and-run tactics and as a scout hunter.', "This update of the COM-5S introduced in 3059 is also built on an Endo Steel chassis but uses a new Light Fusion engine. The ''Mech carries two Streak SRM-2 launchers, an SRM-4 with an Artemis IV Fire Control System, and an ER Medium Laser in each arm.", "In 2463 Coventry Metal Works (then known as Coventry Defense Conglomerate) introduced their second BattleMech, the COM-1A Commando. The Commando was able to destroy much heavier Kuritan Gladiators during the first large-scale battle between BattleMechs in 2475 on Nox. The installed Large Laser caused several problems and other ''Mechs were soon introduced (like the Wasp in 2464 and the Stinger in 2479) that were better equipped for scouting and even mounted jump jets. The Commando''s profile was radically changed with the introduction of the sophisticated COM-2D variant in 2486, which exchanged the laser weaponry with short range missiles and turned the machine into a striker. The Commando became popular among LCAF forces and, nearly 600 years later, is still mainly in use by Lyrans. The Commonwealth went to great pains to keep the ''Mech solely in Lyran hands, especially during the years of the Star League. It took an alliance with the Federated Suns and the creation of the Federated Commonwealth to break the stranglehold. The Commando was chosen as the standard light BattleMech for the Armed Forces of the Federated Commonwealth next to the Valkyrie, and after the upgrade to the COM-5S model in 3050, Vandenberg Mechanized Industries was allowed to produce the old COM-2D for the Taurian Defense Force. Furthermore, the Marian Hegemony deploys the Rocket Launcher-packed COM-4H, and the Word of Blake produced its own variant (the COM-7B) during its occupation of Coventry from 3068 to 3074.");