INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (355417, 'Commando', 'COM-7B', '675', '25', 'Striker', 'Biped', 'Inner Sphere', '3068', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (355417, 355417, '150 Light Engine', 'Endo Steel', 'Standard', '10 Double', '6', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (355417, 355417, 'Standard', 'LA Armor', '6');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (355417, 355417, 'Standard', 'RA Armor', '6');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (355417, 355417, 'Standard', 'LT Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (355417, 355417, 'Standard', 'RT Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (355417, 355417, 'Standard', 'CT Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (355417, 355417, 'Standard', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (355417, 355417, 'Standard', 'LL Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (355417, 355417, 'Standard', 'RL Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (355417, 355417, 'Standard', 'RTL Armor', '2');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (355417, 355417, 'Standard', 'RTR Armor', '2');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (355417, 355417, 'Standard', 'RTC Armor', '3');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3554171, 355417, '1 ISERMediumLaser', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3554172, 355417, '2 ISFlamer', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3554173, 355417, '2 ISSRM4', 'Center Torso', 'Ammo:25');
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (3554171, 355417, 'low_profile');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554171, 355417, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554172, 355417, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554173, 355417, 'Left Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554174, 355417, 'Left Arm', 'Hand Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554175, 355417, 'Left Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554176, 355417, 'Left Arm', 'ISFlamer');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554177, 355417, 'Left Arm', 'ISFlamer');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554178, 355417, 'Left Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554179, 355417, 'Left Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554180, 355417, 'Left Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554181, 355417, 'Left Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554182, 355417, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554183, 355417, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554184, 355417, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554185, 355417, 'Right Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554186, 355417, 'Right Arm', 'Hand Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554187, 355417, 'Right Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554188, 355417, 'Right Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554189, 355417, 'Right Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554190, 355417, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554191, 355417, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554192, 355417, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554193, 355417, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554194, 355417, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554195, 355417, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554196, 355417, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554197, 355417, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554198, 355417, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554199, 355417, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554200, 355417, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554201, 355417, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554202, 355417, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554203, 355417, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554204, 355417, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554205, 355417, 'Left Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554206, 355417, 'Left Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554207, 355417, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554208, 355417, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554209, 355417, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554210, 355417, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554211, 355417, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554212, 355417, 'Right Torso', 'ISSRM4 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554213, 355417, 'Right Torso', 'ISCASE');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554214, 355417, 'Right Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554215, 355417, 'Right Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554216, 355417, 'Right Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554217, 355417, 'Right Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554218, 355417, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554219, 355417, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554220, 355417, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554221, 355417, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554222, 355417, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554223, 355417, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554224, 355417, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554225, 355417, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554226, 355417, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554227, 355417, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554228, 355417, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554229, 355417, 'Center Torso', 'ISSRM4');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554230, 355417, 'Center Torso', 'ISSRM4');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554231, 355417, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554232, 355417, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554233, 355417, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554234, 355417, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554235, 355417, 'Head', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554236, 355417, 'Head', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554237, 355417, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554238, 355417, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554239, 355417, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554240, 355417, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554241, 355417, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554242, 355417, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554243, 355417, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554244, 355417, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554245, 355417, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554246, 355417, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554247, 355417, 'Left Leg', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554248, 355417, 'Left Leg', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554249, 355417, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554250, 355417, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554251, 355417, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554252, 355417, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554253, 355417, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554254, 355417, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554255, 355417, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554256, 355417, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554257, 355417, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554258, 355417, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554259, 355417, 'Right Leg', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554260, 355417, 'Right Leg', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554261, 355417, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554262, 355417, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554263, 355417, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554264, 355417, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554265, 355417, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3554266, 355417, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (355417, 355417, 'Coventry Metal Works', 'Coventry', 'CHASSIS:Foundation Ultralight Endo Steel');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (355417, 355417, "Created for the Lyran Commonwealth Armed Forces and one of the first 'Mechs ever designed for reconnaissance, the Commando was much lighter and faster than its precursors, though it still utilized primitive BattleMech technology.", 'With only four tons of armor to protect itself, the Commando is not meant to participate in a stand-up fight against heavier enemies, but it excels at hit-and-run tactics and as a scout hunter.', 'Following the conquest of Coventry by the Word of Blake, the Jihadists modified the 7S to meet their specifications. The 7B keeps one ER Medium Laser in the left arm, but adds two Flamers to it, making the 7B a lethal threat to unarmored infantry. A small cockpit makes room for two SRM-4s, which are still fed by a CASE-protected ammunition bin. The weight savings enabled engineers to add enough jump jets to rocket the Commando up to one hundred-twenty meters at a time. They also added an additional ton of armor.', "In 2463 Coventry Metal Works (then known as Coventry Defense Conglomerate) introduced their second BattleMech, the COM-1A Commando. The Commando was able to destroy much heavier Kuritan Gladiators during the first large-scale battle between BattleMechs in 2475 on Nox. The installed Large Laser caused several problems and other 'Mechs were soon introduced (like the Wasp in 2464 and the Stinger in 2479) that were better equipped for scouting and even mounted jump jets. The Commando's profile was radically changed with the introduction of the sophisticated COM-2D variant in 2486, which exchanged the laser weaponry with short range missiles and turned the machine into a striker. The Commando became popular among LCAF forces and, nearly 600 years later, is still mainly in use by Lyrans. The Commonwealth went to great pains to keep the 'Mech solely in Lyran hands, especially during the years of the Star League. It took an alliance with the Federated Suns and the creation of the Federated Commonwealth to break the stranglehold. The Commando was chosen as the standard light BattleMech for the Armed Forces of the Federated Commonwealth next to the Valkyrie, and after the upgrade to the COM-5S model in 3050, Vandenberg Mechanized Industries was allowed to produce the old COM-2D for the Taurian Defense Force. Furthermore, the Marian Hegemony deploys the Rocket Launcher-packed COM-4H, and the Word of Blake produced its own variant (the COM-7B) during its occupation of Coventry from 3068 to 3074.");