INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (438140, 'Cougar', 'B', '705', '35', 'Sniper', 'Biped Omnimech', 'Clan', '3058', '2', 'TRO: 3060');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (438140, 438140, '175 XL (Clan) Engine(IS)', 'Clan Endo Steel', 'Standard', '16 Double', '5', '0');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (438140, 438140, 'Ferro-Fibrous(Clan)', 'LA Armor', '11');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (438140, 438140, 'Ferro-Fibrous(Clan)', 'RA Armor', '11');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (438140, 438140, 'Ferro-Fibrous(Clan)', 'LT Armor', '12');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (438140, 438140, 'Ferro-Fibrous(Clan)', 'RT Armor', '12');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (438140, 438140, 'Ferro-Fibrous(Clan)', 'CT Armor', '14');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (438140, 438140, 'Ferro-Fibrous(Clan)', 'HD Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (438140, 438140, 'Ferro-Fibrous(Clan)', 'LL Armor', '12');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (438140, 438140, 'Ferro-Fibrous(Clan)', 'RL Armor', '12');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (438140, 438140, 'Ferro-Fibrous(Clan)', 'RTL Armor', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (438140, 438140, 'Ferro-Fibrous(Clan)', 'RTR Armor', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (438140, 438140, 'Ferro-Fibrous(Clan)', 'RTC Armor', '5');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (4381401, 438140, 'ER PPC', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (4381402, 438140, 'ER PPC', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (4381403, 438140, 'ER Medium Laser', 'Head', NULL);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (4381401, 438140, 'ubiquitous_clan');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381401, 438140, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381402, 438140, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381403, 438140, 'Left Arm', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381404, 438140, 'Left Arm', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381405, 438140, 'Left Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381406, 438140, 'Left Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381407, 438140, 'Left Arm', 'CLERPPC (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381408, 438140, 'Left Arm', 'CLERPPC (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381409, 438140, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381410, 438140, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381411, 438140, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381412, 438140, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381413, 438140, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381414, 438140, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381415, 438140, 'Right Arm', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381416, 438140, 'Right Arm', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381417, 438140, 'Right Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381418, 438140, 'Right Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381419, 438140, 'Right Arm', 'CLERPPC (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381420, 438140, 'Right Arm', 'CLERPPC (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381421, 438140, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381422, 438140, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381423, 438140, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381424, 438140, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381425, 438140, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381426, 438140, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381427, 438140, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381428, 438140, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381429, 438140, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381430, 438140, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381431, 438140, 'Left Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381432, 438140, 'Left Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381433, 438140, 'Left Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381434, 438140, 'Left Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381435, 438140, 'Left Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381436, 438140, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381437, 438140, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381438, 438140, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381439, 438140, 'Right Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381440, 438140, 'Right Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381441, 438140, 'Right Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381442, 438140, 'Right Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381443, 438140, 'Right Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381444, 438140, 'Right Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381445, 438140, 'Right Torso', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381446, 438140, 'Right Torso', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381447, 438140, 'Right Torso', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381448, 438140, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381449, 438140, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381450, 438140, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381451, 438140, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381452, 438140, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381453, 438140, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381454, 438140, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381455, 438140, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381456, 438140, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381457, 438140, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381458, 438140, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381459, 438140, 'Center Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381460, 438140, 'Center Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381461, 438140, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381462, 438140, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381463, 438140, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381464, 438140, 'Head', 'CLERMediumLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381465, 438140, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381466, 438140, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381467, 438140, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381468, 438140, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381469, 438140, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381470, 438140, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381471, 438140, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381472, 438140, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381473, 438140, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381474, 438140, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381475, 438140, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381476, 438140, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381477, 438140, 'Left Leg', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381478, 438140, 'Left Leg', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381479, 438140, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381480, 438140, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381481, 438140, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381482, 438140, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381483, 438140, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381484, 438140, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381485, 438140, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381486, 438140, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381487, 438140, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381488, 438140, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381489, 438140, 'Right Leg', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381490, 438140, 'Right Leg', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381491, 438140, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381492, 438140, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381493, 438140, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381494, 438140, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381495, 438140, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4381496, 438140, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (438140, 438140, 'Ironhold Alpha Complex', 'Ironhold', 'CHASSIS:JF 3 Light Endo Steel');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (438140, 438140, 'Based on the Adder, the Cougar is a powerful Clan Jade Falcon light OmniMech.', "Though the two ''Mechs are visually similar and share the same weight, the Cougar is slower and better armed than the Adder, replacing its progenitor''s 210 XL Engine with a lighter 175 XL model and mounting just five and a half tons of Ferro-Fibrous armor on an Endo Steel frame to boost the available pod-space to 19 tons. Though some Clan MechWarriors complained that the loss of speed was damning for a light ''Mech, the overall consensus was the increased firepower made up for this lack.", 'Similar to the Adder Prime, the Cougar B uses a pair of ER PPCs for direct fire support. It has an ER Medium Laser for close range. Six additional double heat sinks help to dissipate the heat these weapons generate.', "After the Refusal War with Clan Wolf, the Falcon''s newly-vested Khan Marthe Pryde strove to rebuild her shattered touman, reaping the benefits of efforts by her predecessor Elias Crichell to step up the pace of the Falcon breeding program and to bring new and deadly OmniMechs into service. With regards the latter, the successful introduction of the Fire Falcon, Black Lanner, Night Gyr and Turkina pleased her, but Pryde desired the symbolic goal of a complete Star of new ''Mechs. Recognizing that she''d stretched her Clan''s scientists to the limit to produce those four designs already, Khan Pryde directed her scientists to modify an existing design into an even more deadly machine for the fifth member. The design selected was the Adder, and in using an existing design the Falcon scientists were able to field a virtually new ''Mech in roughly half the time normally required to construct and test a new OmniMech. First seeing service during the fighting on Coventry in 3058, the Cougar quickly spread to other Clans, most notably Clan Smoke Jaguar''s defenders during Operation BULLDOG. The visual similarity to the Adder caught the Inner Sphere forces who faced it on Coventry and Port Arthur off-guard, incorrectly assuming it was the older design and being shocked by the greater firepower the Cougar was capable of unleashing. Remaining popular with the Falcons, the Ironhold facility that produced the Cougar was destroyed by Clan Steel Viper in 3071 during the Wars of Reaving.");