INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (930091, 'Hollander II', 'BZK-F5', '1538', '45', 'Sniper', 'Biped', 'Inner Sphere', '3058', '2', 'TRO: 3055');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (930091, 930091, '225 Fusion Engine', 'Endo Steel', 'Standard', '10 Single', '5', '0');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (930091, 930091, 'Ferro-Fibrous(Inner Sphere)', 'LA Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (930091, 930091, 'Ferro-Fibrous(Inner Sphere)', 'RA Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (930091, 930091, 'Ferro-Fibrous(Inner Sphere)', 'LT Armor', '13');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (930091, 930091, 'Ferro-Fibrous(Inner Sphere)', 'RT Armor', '13');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (930091, 930091, 'Ferro-Fibrous(Inner Sphere)', 'CT Armor', '15');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (930091, 930091, 'Ferro-Fibrous(Inner Sphere)', 'HD Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (930091, 930091, 'Ferro-Fibrous(Inner Sphere)', 'LL Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (930091, 930091, 'Ferro-Fibrous(Inner Sphere)', 'RL Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (930091, 930091, 'Ferro-Fibrous(Inner Sphere)', 'RTL Armor', '6');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (930091, 930091, 'Ferro-Fibrous(Inner Sphere)', 'RTR Armor', '6');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (930091, 930091, 'Ferro-Fibrous(Inner Sphere)', 'RTC Armor', '6');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (9300911, 930091, 'Medium Laser', 'Left Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (9300912, 930091, 'Streak SRM 2', 'Left Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (9300913, 930091, 'Gauss Rifle', 'Right Torso', NULL);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (9300911, 930091, 'reinforced_legs');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300911, 930091, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300912, 930091, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300913, 930091, 'Left Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300914, 930091, 'Left Arm', 'Hand Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300915, 930091, 'Left Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300916, 930091, 'Left Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300917, 930091, 'Left Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300918, 930091, 'Left Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300919, 930091, 'Left Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300920, 930091, 'Left Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300921, 930091, 'Left Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300922, 930091, 'Left Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300923, 930091, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300924, 930091, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300925, 930091, 'Right Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300926, 930091, 'Right Arm', 'Hand Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300927, 930091, 'Right Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300928, 930091, 'Right Arm', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300929, 930091, 'Right Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300930, 930091, 'Right Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300931, 930091, 'Right Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300932, 930091, 'Right Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300933, 930091, 'Right Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300934, 930091, 'Right Arm', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300935, 930091, 'Left Torso', 'Medium Laser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300936, 930091, 'Left Torso', 'ISStreakSRM2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300937, 930091, 'Left Torso', 'IS Streak SRM 2 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300938, 930091, 'Left Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300939, 930091, 'Left Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300940, 930091, 'Left Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300941, 930091, 'Left Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300942, 930091, 'Left Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300943, 930091, 'Left Torso', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300944, 930091, 'Left Torso', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300945, 930091, 'Left Torso', 'Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300946, 930091, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300947, 930091, 'Right Torso', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300948, 930091, 'Right Torso', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300949, 930091, 'Right Torso', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300950, 930091, 'Right Torso', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300951, 930091, 'Right Torso', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300952, 930091, 'Right Torso', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300953, 930091, 'Right Torso', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300954, 930091, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300955, 930091, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300956, 930091, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300957, 930091, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300958, 930091, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300959, 930091, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300960, 930091, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300961, 930091, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300962, 930091, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300963, 930091, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300964, 930091, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300965, 930091, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300966, 930091, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300967, 930091, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300968, 930091, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300969, 930091, 'Center Torso', 'IS Gauss Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300970, 930091, 'Center Torso', 'IS Gauss Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300971, 930091, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300972, 930091, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300973, 930091, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300974, 930091, 'Head', 'Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300975, 930091, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300976, 930091, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300977, 930091, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300978, 930091, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300979, 930091, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300980, 930091, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300981, 930091, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300982, 930091, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300983, 930091, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300984, 930091, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300985, 930091, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300986, 930091, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300987, 930091, 'Left Leg', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300988, 930091, 'Left Leg', 'Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300989, 930091, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300990, 930091, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300991, 930091, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300992, 930091, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300993, 930091, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9300994, 930091, 'Left Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (930091, 930091, None, None, None);
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (930091, 930091, None, None, None, None);