INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (228438, 'Hunchback', 'HBK-6S', '5447', '50', 'Striker', 'Biped', 'Inner Sphere', '3063', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (228438, 228438, '300 XL Engine(IS)', 'IS Endo-Steel', 'Standard', '10 Double', '6', '0');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (228438, 228438, 'Standard(Inner Sphere)', 'LA Armor', '16');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (228438, 228438, 'Standard(Inner Sphere)', 'RA Armor', '16');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (228438, 228438, 'Standard(Inner Sphere)', 'LT Armor', '20');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (228438, 228438, 'Standard(Inner Sphere)', 'RT Armor', '20');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (228438, 228438, 'Standard(Inner Sphere)', 'CT Armor', '26');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (228438, 228438, 'Standard(Inner Sphere)', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (228438, 228438, 'Standard(Inner Sphere)', 'LL Armor', '20');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (228438, 228438, 'Standard(Inner Sphere)', 'RL Armor', '20');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (228438, 228438, 'Standard(Inner Sphere)', 'RTL Armor', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (228438, 228438, 'Standard(Inner Sphere)', 'RTR Armor', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (228438, 228438, 'Standard(Inner Sphere)', 'RTC Armor', '5');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2284381, 228438, 'ER Medium Laser', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2284382, 228438, 'ER Medium Laser', 'Right Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2284383, 228438, 'SRM 6', 'Left Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2284384, 228438, 'LB 20-X AC', 'Right Torso', None);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (2284381, 228438, 'battle_fists_la');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284381, 228438, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284382, 228438, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284383, 228438, 'Left Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284384, 228438, 'Left Arm', 'Hand Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284385, 228438, 'Left Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284386, 228438, 'Left Arm', 'IS Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284387, 228438, 'Left Arm', 'IS Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284388, 228438, 'Left Arm', 'IS Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284389, 228438, 'Left Arm', 'IS Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284390, 228438, 'Left Arm', 'IS Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284391, 228438, 'Left Arm', 'IS Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284392, 228438, 'Left Arm', 'IS Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284393, 228438, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284394, 228438, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284395, 228438, 'Right Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284396, 228438, 'Right Arm', 'Hand Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284397, 228438, 'Right Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284398, 228438, 'Right Arm', 'IS Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284399, 228438, 'Right Arm', 'IS Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284400, 228438, 'Right Arm', 'IS Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284401, 228438, 'Right Arm', 'IS Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284402, 228438, 'Right Arm', 'IS Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284403, 228438, 'Right Arm', 'IS Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284404, 228438, 'Right Arm', 'IS Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284405, 228438, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284406, 228438, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284407, 228438, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284408, 228438, 'Left Torso', 'SRM 6');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284409, 228438, 'Left Torso', 'SRM 6');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284410, 228438, 'Left Torso', 'IS Ammo SRM-6');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284411, 228438, 'Left Torso', 'IS LB 20-X AC Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284412, 228438, 'Left Torso', 'IS LB 20-X Cluster Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284413, 228438, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284414, 228438, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284415, 228438, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284416, 228438, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284417, 228438, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284418, 228438, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284419, 228438, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284420, 228438, 'Right Torso', 'ISLBXAC20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284421, 228438, 'Right Torso', 'ISLBXAC20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284422, 228438, 'Right Torso', 'ISLBXAC20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284423, 228438, 'Right Torso', 'ISLBXAC20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284424, 228438, 'Right Torso', 'ISLBXAC20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284425, 228438, 'Right Torso', 'ISLBXAC20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284426, 228438, 'Right Torso', 'ISLBXAC20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284427, 228438, 'Right Torso', 'ISLBXAC20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284428, 228438, 'Right Torso', 'ISLBXAC20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284429, 228438, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284430, 228438, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284431, 228438, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284432, 228438, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284433, 228438, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284434, 228438, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284435, 228438, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284436, 228438, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284437, 228438, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284438, 228438, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284439, 228438, 'Center Torso', 'ISLBXAC20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284440, 228438, 'Center Torso', 'ISLBXAC20');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284441, 228438, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284442, 228438, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284443, 228438, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284444, 228438, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284445, 228438, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284446, 228438, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284447, 228438, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284448, 228438, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284449, 228438, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284450, 228438, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284451, 228438, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284452, 228438, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284453, 228438, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284454, 228438, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284455, 228438, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284456, 228438, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284457, 228438, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284458, 228438, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284459, 228438, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284460, 228438, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284461, 228438, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284462, 228438, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284463, 228438, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284464, 228438, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284465, 228438, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284466, 228438, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284467, 228438, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284468, 228438, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284469, 228438, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284470, 228438, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284471, 228438, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284472, 228438, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284473, 228438, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284474, 228438, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284475, 228438, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2284476, 228438, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (228438, 228438, 'Coventry Metal Works', 'Coventry', 'CHASSIS:Crucis Type V Endo-Steel');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (228438, 228438, 'The Hunchback is a respected and feared Reunification War-era street fighter that has been in production since its introduction in 2572.', "Built for urban combat and close range brawling, this BattleMech has the heavy armor and weaponry to stand up against any foe in the dense cover of a city environment. Its heavy armament does come at a cost: in terms of maneuverability and heat dissipation the Hunchback is merely average, while the lack of long-range weapons means the Hunchback is little more than a slow moving target in the open. In an attack the slow speed of the Hunchback forces it to participate as part of the second wave, exploiting any weaknesses in the enemy's armor after they've been softened up.", 'This variant uses an Endo Steel chassis and 300 rated XL Engine to save weight. The larger engine allows it to reach a top speed of 96km/h. It carries an ER Medium Laser in each arm and a single SRM-6 in the left torso. The main hitting power comes from an LB 20-X autocannon in the right torso. The SRM has a ton of ammunition, while the autocannon has two tons of ammo. It is protected by ten tons of armor and carries ten double heat sinks.', 'The Hunchback was originally designed and produced by Komiyaba/Nissan General Industries and sold throughout the Inner Sphere and Periphery, often fielded as part of medium and assault lances. The company was destroyed in the Succession Wars, but the Hunchback continued to remain popular, especially in the arsenals of House Kurita and House Liao where it fit the dueling nature and all-or-nothing combat styles of the two Successor States. Eventually Kali Yama Weapons Industries bought the rights to the Hunchback and restarted production at their factory on Kalidasa to supply House Marik with large numbers of the \'Mech. Dwindling stockpiles of spare parts and personal preference led many owners to remove the Hunchbacks large signature autocannon and typically install smaller weapons in larger numbers in its stead, resulting in a variety of variants collectively known as "Swayback\'" because of the significant change to the \'Mech\'s configuration and torso structure. The rediscovery of lost technology in the years prior to the Clan Invasion inspired a number of old designs to be upgraded, the Hunchback included. Under contract from the Free Worlds League Military, Kali Yama engineers designed a variant, the HBK-5M, which sought to improve upon the original while still maintaining the "soul" of the machine. While the new variant included several improvements, mostly involving extra protection against ammunition explosions and overheating, to the chagrin of many MechWarriors this came at the cost of reduced ammunition for the autocannon. Their objections ignored, production began in 3046. The new variant came into widespread use throughout the FWLM until Operation Guerrero, when this drawback was responsible for the failure of several advances. After this, Kali Yama finally produced a new variant–the HBK-6M–which addressed this concern. In the years since, Norse-Storm BattleMechs opened a refit line to produce new Hunchback variants and the \'Mech saw use on both sides in the Jihad.');