INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (59817, 'Lao Hu', 'LHU-3B', '4479', None, 'Skirmisher', 'Biped', None, None, None, None);
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (59817, 59817, None, None, None, None, None, None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (598171, 59817, 'ER Large Laser', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (598172, 59817, 'LB 10-X AC', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (598173, 59817, 'LRM 10', 'Left Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (598174, 59817, 'C3 Computer [Master]', 'Right Torso', NULL);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (598171, 59817, 'good_rep_1');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598171, 59817, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598172, 59817, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598173, 59817, 'Left Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598174, 59817, 'Left Arm', 'ISERLargeLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598175, 59817, 'Left Arm', 'ISERLargeLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598176, 59817, 'Left Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598177, 59817, 'Left Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598178, 59817, 'Left Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598179, 59817, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598180, 59817, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598181, 59817, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598182, 59817, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598183, 59817, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598184, 59817, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598185, 59817, 'Right Arm', 'ISLBXAC10');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598186, 59817, 'Right Arm', 'ISLBXAC10');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598187, 59817, 'Right Arm', 'ISLBXAC10');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598188, 59817, 'Right Arm', 'ISLBXAC10');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598189, 59817, 'Right Arm', 'ISLBXAC10');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598190, 59817, 'Right Arm', 'ISLBXAC10');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598191, 59817, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598192, 59817, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598193, 59817, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598194, 59817, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598195, 59817, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598196, 59817, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598197, 59817, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598198, 59817, 'Left Torso', 'LRM 10');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598199, 59817, 'Left Torso', 'LRM 10');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598200, 59817, 'Left Torso', 'ISArtemisIV');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598201, 59817, 'Left Torso', 'IS Ammo LRM-10 Artemis-capable');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598202, 59817, 'Left Torso', 'IS Ammo LRM-10 Artemis-capable');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598203, 59817, 'Left Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598204, 59817, 'Left Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598205, 59817, 'Left Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598206, 59817, 'Left Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598207, 59817, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598208, 59817, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598209, 59817, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598210, 59817, 'Right Torso', 'IS LB 10-X AC Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598211, 59817, 'Right Torso', 'IS LB 10-X Cluster Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598212, 59817, 'Right Torso', 'IS LB 10-X Cluster Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598213, 59817, 'Right Torso', 'ISC3MasterUnit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598214, 59817, 'Right Torso', 'ISC3MasterUnit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598215, 59817, 'Right Torso', 'ISC3MasterUnit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598216, 59817, 'Right Torso', 'ISC3MasterUnit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598217, 59817, 'Right Torso', 'ISC3MasterUnit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598218, 59817, 'Right Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598219, 59817, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598220, 59817, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598221, 59817, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598222, 59817, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598223, 59817, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598224, 59817, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598225, 59817, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598226, 59817, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598227, 59817, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598228, 59817, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598229, 59817, 'Center Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598230, 59817, 'Center Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598231, 59817, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598232, 59817, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598233, 59817, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598234, 59817, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598235, 59817, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598236, 59817, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598237, 59817, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598238, 59817, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598239, 59817, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598240, 59817, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598241, 59817, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598242, 59817, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598243, 59817, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598244, 59817, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598245, 59817, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598246, 59817, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598247, 59817, 'Left Leg', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598248, 59817, 'Left Leg', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598249, 59817, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598250, 59817, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598251, 59817, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598252, 59817, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598253, 59817, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598254, 59817, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598255, 59817, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598256, 59817, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598257, 59817, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598258, 59817, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598259, 59817, 'Right Leg', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598260, 59817, 'Right Leg', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598261, 59817, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598262, 59817, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598263, 59817, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598264, 59817, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598265, 59817, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (598266, 59817, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (59817, 59817, 'Shengli Arms', 'Victoria', 'CHASSIS:Chariot Type II Endo Steel');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (59817, 59817, 'Designed by a student at the Victoria Academy of Arms and Technology, the Lao Hu ("Tiger") is based on the Thunder BattleMech and is designed to correct perceived flaws in the Thunder by using new technologies available to the Capellan Confederation.', "The Lao Hu is built on a lightweight Chariot Type II Endo Steel that carries a GM 375 XL Engine which gives the ''Mech a top speed of 86.4 km/h while sacrificing some survivability for more free weight and a heavier weapons payload. The Lao Hu is protected by an impressive thirteen and a half tons of armor, making it capable of weathering hits from all but the heaviest weapons.", "Modified to carry a C3 Master Computer, the 3B downgrades its autocannon to an LB 10-X AC, drops a ton of armor and replaces the LRM-15 with an LRM-10 with an Artemis IV FCS. The 3B uses its C3 computer to link together an entire C3 Lance and gives the ''Mech unparalleled accuracy when part of a C3 lance.", None);