INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (807116, 'Lao Hu', 'LHU-3C', '4480', '75', 'Sniper', 'Biped', 'Inner Sphere', '3064', '2', None);
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (807116, 807116, '375 XL Engine', 'Endo Steel', 'Standard', '10 Double', '5', '0');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (807116, 807116, 'Standard Armor', 'LA Armor', '23');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (807116, 807116, 'Standard Armor', 'RA Armor', '23');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (807116, 807116, 'Standard Armor', 'LT Armor', '24');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (807116, 807116, 'Standard Armor', 'RT Armor', '24');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (807116, 807116, 'Standard Armor', 'CT Armor', '33');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (807116, 807116, 'Standard Armor', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (807116, 807116, 'Standard Armor', 'LL Armor', '28');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (807116, 807116, 'Standard Armor', 'RL Armor', '28');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (807116, 807116, 'Standard Armor', 'RTL Armor', '7');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (807116, 807116, 'Standard Armor', 'RTR Armor', '7');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (807116, 807116, 'Standard Armor', 'RTC Armor', '10');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (8071161, 807116, '1 ISGaussRifle', 'Right Arm', 'Ammo:16');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (8071162, 807116, '1 ISERLargeLaser', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (8071163, 807116, '3 ISLRM5', 'Left Torso', 'Ammo:72');
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (8071161, 807116, 'good_rep_1');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071161, 807116, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071162, 807116, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071163, 807116, 'Left Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071164, 807116, 'Left Arm', 'ISERLargeLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071165, 807116, 'Left Arm', 'ISERLargeLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071166, 807116, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071167, 807116, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071168, 807116, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071169, 807116, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071170, 807116, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071171, 807116, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071172, 807116, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071173, 807116, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071174, 807116, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071175, 807116, 'Right Arm', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071176, 807116, 'Right Arm', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071177, 807116, 'Right Arm', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071178, 807116, 'Right Arm', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071179, 807116, 'Right Arm', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071180, 807116, 'Right Arm', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071181, 807116, 'Right Arm', 'ISGaussRifle');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071182, 807116, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071183, 807116, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071184, 807116, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071185, 807116, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071186, 807116, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071187, 807116, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071188, 807116, 'Left Torso', 'ISLRM5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071189, 807116, 'Left Torso', 'ISLRM5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071190, 807116, 'Left Torso', 'ISLRM5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071191, 807116, 'Left Torso', 'ISLRM5 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071192, 807116, 'Left Torso', 'ISLRM5 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071193, 807116, 'Left Torso', 'ISLRM5 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071194, 807116, 'Left Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071195, 807116, 'Left Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071196, 807116, 'Left Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071197, 807116, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071198, 807116, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071199, 807116, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071200, 807116, 'Right Torso', 'ISGauss Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071201, 807116, 'Right Torso', 'ISGauss Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071202, 807116, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071203, 807116, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071204, 807116, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071205, 807116, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071206, 807116, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071207, 807116, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071208, 807116, 'Right Torso', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071209, 807116, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071210, 807116, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071211, 807116, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071212, 807116, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071213, 807116, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071214, 807116, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071215, 807116, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071216, 807116, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071217, 807116, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071218, 807116, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071219, 807116, 'Center Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071220, 807116, 'Center Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071221, 807116, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071222, 807116, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071223, 807116, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071224, 807116, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071225, 807116, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071226, 807116, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071227, 807116, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071228, 807116, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071229, 807116, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071230, 807116, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071231, 807116, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071232, 807116, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071233, 807116, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071234, 807116, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071235, 807116, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071236, 807116, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071237, 807116, 'Left Leg', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071238, 807116, 'Left Leg', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071239, 807116, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071240, 807116, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071241, 807116, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071242, 807116, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071243, 807116, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071244, 807116, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071245, 807116, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071246, 807116, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071247, 807116, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071248, 807116, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071249, 807116, 'Right Leg', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071250, 807116, 'Right Leg', 'Endo-Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071251, 807116, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071252, 807116, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071253, 807116, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071254, 807116, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071255, 807116, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8071256, 807116, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (807116, 807116, 'Shengli Arms', 'Victoria', 'CHASSIS:Chariot Type II Endo Steel');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (807116, 807116, 'Designed by a student at the Victoria Academy of Arms and Technology, the Lao Hu ("Tiger") is based on the Thunder BattleMech and is designed to correct perceived flaws in the Thunder by using new technologies available to the Capellan Confederation.', "The Lao Hu is built on a lightweight Chariot Type II Endo Steel that carries a GM 375 XL Engine which gives the 'Mech a top speed of 86.4 km/h while sacrificing some survivability for more free weight and a heavier weapons payload. The Lao Hu is protected by an impressive thirteen and a half tons of armor, making it capable of weathering hits from all but the heaviest weapons.", "The 3C is intended to spar with its enemies at long range. The 'Mech replaced the LB 20-X AC with a powerful Gauss Rifle. Additionally, the 3C removed the LRM-15 in favor of three LRM-5 launchers, giving it the same firepower but allowing it to spread it over a greater number of targets.", None);