INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (506414, 'Masakari', 'H', '2096', '85', 'Brawler', 'Biped Omnimech', 'Clan', '3059', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (506414, 506414, '340 XL (Clan) Engine(IS)', 'IS Standard', 'Standard', '25 Double', '4', '0');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (506414, 506414, 'Ferro-Fibrous(Clan)', 'LA Armor', '28');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (506414, 506414, 'Ferro-Fibrous(Clan)', 'RA Armor', '28');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (506414, 506414, 'Ferro-Fibrous(Clan)', 'LT Armor', '26');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (506414, 506414, 'Ferro-Fibrous(Clan)', 'RT Armor', '26');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (506414, 506414, 'Ferro-Fibrous(Clan)', 'CT Armor', '42');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (506414, 506414, 'Ferro-Fibrous(Clan)', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (506414, 506414, 'Ferro-Fibrous(Clan)', 'LL Armor', '35');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (506414, 506414, 'Ferro-Fibrous(Clan)', 'RL Armor', '35');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (506414, 506414, 'Ferro-Fibrous(Clan)', 'RTL Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (506414, 506414, 'Ferro-Fibrous(Clan)', 'RTR Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (506414, 506414, 'Ferro-Fibrous(Clan)', 'RTC Armor', '10');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5064141, 506414, 'Heavy Large Laser', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5064142, 506414, 'Heavy Large Laser', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5064143, 506414, 'Large Pulse Laser', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5064144, 506414, 'Large Pulse Laser', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5064145, 506414, 'LRM 10', 'Right Arm', NULL);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (5064141, 506414, 'imp_target_long');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064141, 506414, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064142, 506414, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064143, 506414, 'Left Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064144, 506414, 'Left Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064145, 506414, 'Left Arm', 'CLHeavyLargeLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064146, 506414, 'Left Arm', 'CLHeavyLargeLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064147, 506414, 'Left Arm', 'CLHeavyLargeLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064148, 506414, 'Left Arm', 'CLHeavyLargeLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064149, 506414, 'Left Arm', 'CLHeavyLargeLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064150, 506414, 'Left Arm', 'CLHeavyLargeLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064151, 506414, 'Left Arm', 'Clan Ammo LRM-10 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064152, 506414, 'Left Arm', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064153, 506414, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064154, 506414, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064155, 506414, 'Right Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064156, 506414, 'Right Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064157, 506414, 'Right Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064158, 506414, 'Right Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064159, 506414, 'Right Arm', 'CLLargePulseLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064160, 506414, 'Right Arm', 'CLLargePulseLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064161, 506414, 'Right Arm', 'CLLargePulseLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064162, 506414, 'Right Arm', 'CLLargePulseLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064163, 506414, 'Right Arm', 'CLLRM10 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064164, 506414, 'Right Arm', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064165, 506414, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064166, 506414, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064167, 506414, 'Left Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064168, 506414, 'Left Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064169, 506414, 'Left Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064170, 506414, 'Left Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064171, 506414, 'Left Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064172, 506414, 'Left Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064173, 506414, 'Left Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064174, 506414, 'Left Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064175, 506414, 'Left Torso', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064176, 506414, 'Left Torso', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064177, 506414, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064178, 506414, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064179, 506414, 'Right Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064180, 506414, 'Right Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064181, 506414, 'Right Torso', 'CLTargeting Computer (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064182, 506414, 'Right Torso', 'CLTargeting Computer (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064183, 506414, 'Right Torso', 'CLTargeting Computer (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064184, 506414, 'Right Torso', 'CLTargeting Computer (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064185, 506414, 'Right Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064186, 506414, 'Right Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064187, 506414, 'Right Torso', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064188, 506414, 'Right Torso', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064189, 506414, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064190, 506414, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064191, 506414, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064192, 506414, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064193, 506414, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064194, 506414, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064195, 506414, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064196, 506414, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064197, 506414, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064198, 506414, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064199, 506414, 'Center Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064200, 506414, 'Center Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064201, 506414, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064202, 506414, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064203, 506414, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064204, 506414, 'Head', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064205, 506414, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064206, 506414, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064207, 506414, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064208, 506414, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064209, 506414, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064210, 506414, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064211, 506414, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064212, 506414, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064213, 506414, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064214, 506414, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064215, 506414, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064216, 506414, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064217, 506414, 'Left Leg', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064218, 506414, 'Left Leg', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064219, 506414, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064220, 506414, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064221, 506414, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064222, 506414, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064223, 506414, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064224, 506414, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064225, 506414, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064226, 506414, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064227, 506414, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064228, 506414, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064229, 506414, 'Right Leg', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064230, 506414, 'Right Leg', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064231, 506414, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064232, 506414, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064233, 506414, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064234, 506414, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064235, 506414, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5064236, 506414, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (506414, 506414, 'Phan Industrialplex,Abysmal Manufacturing Complex,Kindraa Kline Primary Production Facility,Imperial BattleMechs', 'Huntress,Huntress,Dagda,Antwerp', 'CHASSIS:Huntress WH');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (506414, 506414, 'Introduced by Clan Smoke Jaguar in 2999 in preparation for the anticipated return to the Inner Sphere, while the Dragoon Compromise stalled such plans, the Jaguars unleashed the powerful Warhawk on their Warden opponents to deadly effect.', 'The Warhawk was powered by a massive 340 XL Engine that gave it a top speed of 64.8 km/h and mounted thirteen and a half tons of Ferro-Fibrous armor to protect itself from enemy fire. To dissipate the massive waste heat produced in its various configurations, it carried a staggering twenty double heat sinks. Additionally, though not truly fixed equipment on the chassis, the Warhawk managed to incorporate an advanced Targeting Computer into each of its configurations, making all of its direct fire weapons extremely accurate.', "A close combat configuration of the Warhawk, the H configuration carried as its only true long range weapon an LRM-10 launcher. This was backed up by a pair of Large Pulse Lasers and also a pair of Heavy Large Lasers which gave the ''Mech incredible close range damage potential. To handle the heavy heat load, the Warhawk H carried an additional five double heat sinks.", "Deployed extensively in the Jaguar frontline forces, and often seen paired with the Dire Wolf, the design truly came to prominence as originally intended, on the battlefields of the Jaguars'' Invasion Corridor and earned the code name of Masakari - a Japanese battle-axe used on medieval Terra - from warriors within the DCMS who faced it. Though it appeared in the Toumans of a number of other Clans, such as the Ghost Bears and Jade Falcons, the Jaguars jealously guarded their production, and all examples of the highly prized ''Mech outside of the Jaguars were battlefield salvage until production lines and design specs finally spread to the Fire Mandrills, Diamond Sharks and Goliath Scorpions upon the Smoke Jaguars'' Annihilation. Produced exclusively on the Clan Homeworlds, the design was one of many lost to the Inner Sphere Clans after contact with the Homeworlds ceased during the Jihad.");