INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (332035, 'Mauler', 'MAL-2R', '5460', '90', 'Juggernaut', 'Biped', 'Inner Sphere', '3060', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (332035, 332035, '270 Fusion Engine(IS)', 'IS Standard', 'Standard', '12 Double', '3', '0');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (332035, 332035, 'Ferro-Fibrous(Inner Sphere)', 'LA Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (332035, 332035, 'Ferro-Fibrous(Inner Sphere)', 'RA Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (332035, 332035, 'Ferro-Fibrous(Inner Sphere)', 'LT Armor', '26');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (332035, 332035, 'Ferro-Fibrous(Inner Sphere)', 'RT Armor', '26');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (332035, 332035, 'Ferro-Fibrous(Inner Sphere)', 'CT Armor', '27');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (332035, 332035, 'Ferro-Fibrous(Inner Sphere)', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (332035, 332035, 'Ferro-Fibrous(Inner Sphere)', 'LL Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (332035, 332035, 'Ferro-Fibrous(Inner Sphere)', 'RL Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (332035, 332035, 'Ferro-Fibrous(Inner Sphere)', 'RTL Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (332035, 332035, 'Ferro-Fibrous(Inner Sphere)', 'RTR Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (332035, 332035, 'Ferro-Fibrous(Inner Sphere)', 'RTC Armor', '10');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3320351, 332035, 'ER Medium Laser', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3320352, 332035, 'ER Medium Laser', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3320353, 332035, 'ER Medium Laser', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3320354, 332035, 'ER Medium Laser', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3320355, 332035, 'Ultra AC/2', 'Left Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3320356, 332035, 'Ultra AC/2', 'Right Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3320357, 332035, 'Ultra AC/2', 'Right Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3320358, 332035, 'Ultra AC/2', 'Left Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3320359, 332035, 'LRM 10', 'Right Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3320360, 332035, 'LRM 10', 'Left Torso', NULL);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (3320351, 332035, 'stable_weapon:RT:2:ISUltraAC2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320351, 332035, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320352, 332035, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320353, 332035, 'Left Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320354, 332035, 'Left Arm', 'ISDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320355, 332035, 'Left Arm', 'ISDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320356, 332035, 'Left Arm', 'ISDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320357, 332035, 'Left Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320358, 332035, 'Left Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320359, 332035, 'Left Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320360, 332035, 'Left Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320361, 332035, 'Left Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320362, 332035, 'Left Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320363, 332035, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320364, 332035, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320365, 332035, 'Right Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320366, 332035, 'Right Arm', 'ISDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320367, 332035, 'Right Arm', 'ISDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320368, 332035, 'Right Arm', 'ISDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320369, 332035, 'Right Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320370, 332035, 'Right Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320371, 332035, 'Right Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320372, 332035, 'Right Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320373, 332035, 'Right Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320374, 332035, 'Right Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320375, 332035, 'Left Torso', 'LRM 10');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320376, 332035, 'Left Torso', 'LRM 10');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320377, 332035, 'Left Torso', 'ISUltraAC2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320378, 332035, 'Left Torso', 'ISUltraAC2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320379, 332035, 'Left Torso', 'ISUltraAC2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320380, 332035, 'Left Torso', 'ISUltraAC2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320381, 332035, 'Left Torso', 'ISUltraAC2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320382, 332035, 'Left Torso', 'ISUltraAC2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320383, 332035, 'Left Torso', 'IS Ultra AC/2 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320384, 332035, 'Left Torso', 'IS Ammo LRM-10');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320385, 332035, 'Left Torso', 'ISCASE');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320386, 332035, 'Left Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320387, 332035, 'Right Torso', 'LRM 10');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320388, 332035, 'Right Torso', 'LRM 10');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320389, 332035, 'Right Torso', 'ISUltraAC2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320390, 332035, 'Right Torso', 'ISUltraAC2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320391, 332035, 'Right Torso', 'ISUltraAC2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320392, 332035, 'Right Torso', 'ISUltraAC2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320393, 332035, 'Right Torso', 'ISUltraAC2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320394, 332035, 'Right Torso', 'ISUltraAC2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320395, 332035, 'Right Torso', 'IS Ultra AC/2 Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320396, 332035, 'Right Torso', 'IS Ammo LRM-10');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320397, 332035, 'Right Torso', 'ISCASE');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320398, 332035, 'Right Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320399, 332035, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320400, 332035, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320401, 332035, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320402, 332035, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320403, 332035, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320404, 332035, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320405, 332035, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320406, 332035, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320407, 332035, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320408, 332035, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320409, 332035, 'Center Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320410, 332035, 'Center Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320411, 332035, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320412, 332035, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320413, 332035, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320414, 332035, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320415, 332035, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320416, 332035, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320417, 332035, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320418, 332035, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320419, 332035, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320420, 332035, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320421, 332035, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320422, 332035, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320423, 332035, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320424, 332035, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320425, 332035, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320426, 332035, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320427, 332035, 'Left Leg', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320428, 332035, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320429, 332035, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320430, 332035, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320431, 332035, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320432, 332035, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320433, 332035, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320434, 332035, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320435, 332035, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320436, 332035, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320437, 332035, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320438, 332035, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320439, 332035, 'Right Leg', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320440, 332035, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320441, 332035, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320442, 332035, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320443, 332035, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320444, 332035, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320445, 332035, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3320446, 332035, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (332035, 332035, 'Luthien Armor Works, Luthien Armor Works', 'New Samarkand,Luthien', 'CHASSIS:Alshain Class 101');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (332035, 332035, "The Mauler''s arsenal is primarily focused on long-range engagements, featuring a combination of light autocannons and missile systems, supplemented by energy weapons. This loadout allows the Mauler to excel in support roles, offering sustained fire from a distance. Despite its impressive offensive capabilities, the Mech''s limited heat dissipation can pose challenges during intense combat, necessitating careful heat management by its pilots. Its eleven and a half tons of ferro-fibrous armor provide substantial protection, but its top speed of 54 km/h limits its mobility on the battlefield.", "<p>At its core, the Mauler is equipped with a formidable array of weaponry, primarily geared towards long-range engagements. This includes extended-range lasers and LRM launchers, allowing it to deliver powerful strikes from a distance. The integration of these advanced weapon systems, coupled with an extra-light engine, significantly enhances its offensive capabilities, making it a formidable opponent in ranged combat scenarios.</p><p>Defensively, the Mauler is protected by a robust arrangement of ferro-fibrous armor, providing substantial resilience against enemy fire. Its defensive prowess is further augmented by the sophisticated CASE system, designed to protect the pilot from critical damage. The Mauler''s speed, capped at 54 km/h, is optimized for maintaining optimal distance in combat, enabling it to leverage its long-range weaponry effectively while minimizing exposure to enemy attacks.</p><p>The unique technological aspects of the Mauler include its advanced heat sink system, crucial for managing the heat generated by its high-powered armaments. This system allows the Mauler to sustain prolonged engagements, delivering consistent firepower without the risk of overheating. Additionally, the Mauler''s design prioritizes ammunition efficiency, ensuring a steady supply for its ballistic and missile-based weaponry, crucial for maintaining its combat effectiveness in extended battles.</p>", '<p>The Mauler variant, a 90-ton bipedal Mech designed for the juggernaut role, is built for long-range engagements. It is powered by a 270 Fusion Engine and constructed with a standard Inner Sphere structure for durability. This variant is armed with four Ultra AC/2s, two in each side torso, which are known for their rapid fire capability. The armament also includes eight ER Medium Lasers, distributed evenly in the arms, and two LRM 10 launchers, one in each side torso. The Mech is protected by Ferro-Fibrous armor, providing substantial defense against enemy attacks. To manage heat from its extensive weaponry, it is equipped with 12 Double Heat Sinks. This configuration offers a balance of high-rate fire from the autocannons and sustained energy weapon strikes, making it effective in its designated role.</p>', "The Mauler, initially developed as the Daboku by Luthien Armor Works (LAW), originated from a Draconis Combine initiative in 3036. This project aimed to capitalize on advanced Star League technology from the Helm Memory Core and ComStar''s contributions. The design was intended to mirror the Star League''s Thug using the Charger chassis for streamlined production.");