INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (525978, 'Mauler', 'MAL-1K', '2100', '90', 'Juggernaut', 'Biped', 'Inner Sphere', '3069', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (525978, 525978, '270 XL Engine(IS)', 'IS Standard', 'Standard', '11 Double', '3', '0');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (525978, 525978, 'Ferro-Fibrous(Inner Sphere)', 'LA Armor', '24');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (525978, 525978, 'Ferro-Fibrous(Inner Sphere)', 'RA Armor', '24');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (525978, 525978, 'Ferro-Fibrous(Inner Sphere)', 'LT Armor', '28');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (525978, 525978, 'Ferro-Fibrous(Inner Sphere)', 'RT Armor', '28');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (525978, 525978, 'Ferro-Fibrous(Inner Sphere)', 'CT Armor', '33');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (525978, 525978, 'Ferro-Fibrous(Inner Sphere)', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (525978, 525978, 'Ferro-Fibrous(Inner Sphere)', 'LL Armor', '24');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (525978, 525978, 'Ferro-Fibrous(Inner Sphere)', 'RL Armor', '24');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (525978, 525978, 'Ferro-Fibrous(Inner Sphere)', 'RTL Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (525978, 525978, 'Ferro-Fibrous(Inner Sphere)', 'RTR Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (525978, 525978, 'Ferro-Fibrous(Inner Sphere)', 'RTC Armor', '10');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5259781, 525978, 'Snub-Nose PPC', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5259782, 525978, 'Snub-Nose PPC', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5259783, 525978, 'LRM 15', 'Left Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5259784, 525978, 'LAC/5', 'Right Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5259785, 525978, 'LAC/5', 'Left Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5259786, 525978, 'LRM 15', 'Right Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5259787, 525978, 'LAC/5', 'Left Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (5259788, 525978, 'LAC/5', 'Right Torso', NULL);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (5259781, 525978, 'stable_weapon:RT:6:Light Auto Cannon/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259781, 525978, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259782, 525978, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259783, 525978, 'Left Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259784, 525978, 'Left Arm', 'ISDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259785, 525978, 'Left Arm', 'ISDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259786, 525978, 'Left Arm', 'ISDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259787, 525978, 'Left Arm', 'ISSNPPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259788, 525978, 'Left Arm', 'ISSNPPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259789, 525978, 'Left Arm', 'IS Ammo LAC/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259790, 525978, 'Left Arm', 'IS Ammo LAC/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259791, 525978, 'Left Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259792, 525978, 'Left Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259793, 525978, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259794, 525978, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259795, 525978, 'Right Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259796, 525978, 'Right Arm', 'ISSNPPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259797, 525978, 'Right Arm', 'ISSNPPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259798, 525978, 'Right Arm', 'IS Ammo LAC/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259799, 525978, 'Right Arm', 'IS Ammo LAC/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259800, 525978, 'Right Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259801, 525978, 'Right Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259802, 525978, 'Right Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259803, 525978, 'Right Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259804, 525978, 'Right Arm', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259805, 525978, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259806, 525978, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259807, 525978, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259808, 525978, 'Left Torso', 'LRM 15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259809, 525978, 'Left Torso', 'LRM 15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259810, 525978, 'Left Torso', 'LRM 15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259811, 525978, 'Left Torso', 'Light Auto Cannon/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259812, 525978, 'Left Torso', 'Light Auto Cannon/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259813, 525978, 'Left Torso', 'Light Auto Cannon/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259814, 525978, 'Left Torso', 'Light Auto Cannon/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259815, 525978, 'Left Torso', 'IS Ammo LRM-15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259816, 525978, 'Left Torso', 'IS Ammo LRM-15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259817, 525978, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259818, 525978, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259819, 525978, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259820, 525978, 'Right Torso', 'LRM 15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259821, 525978, 'Right Torso', 'LRM 15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259822, 525978, 'Right Torso', 'LRM 15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259823, 525978, 'Right Torso', 'Light Auto Cannon/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259824, 525978, 'Right Torso', 'Light Auto Cannon/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259825, 525978, 'Right Torso', 'Light Auto Cannon/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259826, 525978, 'Right Torso', 'Light Auto Cannon/5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259827, 525978, 'Right Torso', 'IS Ammo LRM-15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259828, 525978, 'Right Torso', 'IS Ammo LRM-15');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259829, 525978, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259830, 525978, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259831, 525978, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259832, 525978, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259833, 525978, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259834, 525978, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259835, 525978, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259836, 525978, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259837, 525978, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259838, 525978, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259839, 525978, 'Center Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259840, 525978, 'Center Torso', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259841, 525978, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259842, 525978, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259843, 525978, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259844, 525978, 'Head', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259845, 525978, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259846, 525978, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259847, 525978, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259848, 525978, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259849, 525978, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259850, 525978, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259851, 525978, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259852, 525978, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259853, 525978, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259854, 525978, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259855, 525978, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259856, 525978, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259857, 525978, 'Left Leg', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259858, 525978, 'Left Leg', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259859, 525978, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259860, 525978, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259861, 525978, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259862, 525978, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259863, 525978, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259864, 525978, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259865, 525978, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259866, 525978, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259867, 525978, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259868, 525978, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259869, 525978, 'Right Leg', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259870, 525978, 'Right Leg', 'IS Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259871, 525978, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259872, 525978, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259873, 525978, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259874, 525978, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259875, 525978, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (5259876, 525978, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (525978, 525978, 'Luthien Armor Works, Luthien Armor Works', 'New Samarkand,Luthien', 'CHASSIS:Alshain Class 101');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (525978, 525978, "The Mauler''s arsenal is primarily focused on long-range engagements, featuring a combination of light autocannons and missile systems, supplemented by energy weapons. This loadout allows the Mauler to excel in support roles, offering sustained fire from a distance. Despite its impressive offensive capabilities, the Mech''s limited heat dissipation can pose challenges during intense combat, necessitating careful heat management by its pilots. Its eleven and a half tons of ferro-fibrous armor provide substantial protection, but its top speed of 54 km/h limits its mobility on the battlefield.", "<p>At its core, the Mauler is equipped with a formidable array of weaponry, primarily geared towards long-range engagements. This includes extended-range lasers and LRM launchers, allowing it to deliver powerful strikes from a distance. The integration of these advanced weapon systems, coupled with an extra-light engine, significantly enhances its offensive capabilities, making it a formidable opponent in ranged combat scenarios.</p><p>Defensively, the Mauler is protected by a robust arrangement of ferro-fibrous armor, providing substantial resilience against enemy fire. Its defensive prowess is further augmented by the sophisticated CASE system, designed to protect the pilot from critical damage. The Mauler''s speed, capped at 54 km/h, is optimized for maintaining optimal distance in combat, enabling it to leverage its long-range weaponry effectively while minimizing exposure to enemy attacks.</p><p>The unique technological aspects of the Mauler include its advanced heat sink system, crucial for managing the heat generated by its high-powered armaments. This system allows the Mauler to sustain prolonged engagements, delivering consistent firepower without the risk of overheating. Additionally, the Mauler''s design prioritizes ammunition efficiency, ensuring a steady supply for its ballistic and missile-based weaponry, crucial for maintaining its combat effectiveness in extended battles.</p>", "The MAL-1K Mauler is a versatile assault BattleMech, distinguished by its 270 XL Engine, which balances speed with substantial armament capacity. Its chassis is constructed using standard Inner Sphere technology, complemented by standard myomer for reliable performance. The Mech''s durability is enhanced with Ferro-Fibrous armor, offering superior protection with reduced weight. Its armament includes two Snub-Nose Particle Projection Cannons, one in each arm, for effective mid-range firepower. Additionally, it is equipped with two LRM-15 launchers, one on each side of the torso, for long-range engagements. The MAL-1K further bolsters its firepower with four Light Autocannon/5s, two mounted in each side of the torso, providing a balanced mix of ballistic firepower. This combination of weapons allows the MAL-1K to engage effectively at various combat ranges, making it a formidable opponent on the battlefield.", "The Mauler, initially developed as the Daboku by Luthien Armor Works (LAW), originated from a Draconis Combine initiative in 3036. This project aimed to capitalize on advanced Star League technology from the Helm Memory Core and ComStar''s contributions. The design was intended to mirror the Star League''s Thug using the Charger chassis for streamlined production.");