INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (986914, 'Nova Cat', 'E', '2303', '70', 'Brawler', 'Biped Omnimech', 'Clan', '3064', '2', 'TRO: 3060');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (986914, 986914, '280 XL (Clan) Engine(IS)', 'Clan Endo Steel', 'Standard', '15 Double', '4', '0');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (986914, 986914, 'Standard(Clan)', 'LA Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (986914, 986914, 'Standard(Clan)', 'RA Armor', '22');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (986914, 986914, 'Standard(Clan)', 'LT Armor', '23');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (986914, 986914, 'Standard(Clan)', 'RT Armor', '23');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (986914, 986914, 'Standard(Clan)', 'CT Armor', '35');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (986914, 986914, 'Standard(Clan)', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (986914, 986914, 'Standard(Clan)', 'LL Armor', '30');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (986914, 986914, 'Standard(Clan)', 'RL Armor', '30');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (986914, 986914, 'Standard(Clan)', 'RTL Armor', '7');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (986914, 986914, 'Standard(Clan)', 'RTR Armor', '7');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (986914, 986914, 'Standard(Clan)', 'RTC Armor', '8');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (9869141, 986914, 'ATM 9', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (9869142, 986914, 'ATM 9', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (9869143, 986914, 'ATM 9', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (9869144, 986914, 'ATM 9', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (9869145, 986914, 'Large Pulse Laser', 'Right Torso', NULL);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (9869141, 986914, 'ext_twist');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869141, 986914, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869142, 986914, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869143, 986914, 'Left Arm', 'CLATM9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869144, 986914, 'Left Arm', 'CLATM9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869145, 986914, 'Left Arm', 'CLATM9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869146, 986914, 'Left Arm', 'CLATM9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869147, 986914, 'Left Arm', 'CLATM9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869148, 986914, 'Left Arm', 'CLATM9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869149, 986914, 'Left Arm', 'CLATM9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869150, 986914, 'Left Arm', 'CLATM9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869151, 986914, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869152, 986914, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869153, 986914, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869154, 986914, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869155, 986914, 'Right Arm', 'CLATM9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869156, 986914, 'Right Arm', 'CLATM9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869157, 986914, 'Right Arm', 'CLATM9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869158, 986914, 'Right Arm', 'CLATM9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869159, 986914, 'Right Arm', 'CLATM9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869160, 986914, 'Right Arm', 'CLATM9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869161, 986914, 'Right Arm', 'CLATM9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869162, 986914, 'Right Arm', 'CLATM9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869163, 986914, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869164, 986914, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869165, 986914, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869166, 986914, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869167, 986914, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869168, 986914, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869169, 986914, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869170, 986914, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869171, 986914, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869172, 986914, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869173, 986914, 'Left Torso', 'Clan Ammo ATM-9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869174, 986914, 'Left Torso', 'Clan Ammo ATM-9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869175, 986914, 'Left Torso', 'Clan Ammo ATM-9 ER (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869176, 986914, 'Left Torso', 'Clan Ammo ATM-9 HE (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869177, 986914, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869178, 986914, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869179, 986914, 'Right Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869180, 986914, 'Right Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869181, 986914, 'Right Torso', 'CLLargePulseLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869182, 986914, 'Right Torso', 'CLLargePulseLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869183, 986914, 'Right Torso', 'Clan Ammo ATM-9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869184, 986914, 'Right Torso', 'Clan Ammo ATM-9 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869185, 986914, 'Right Torso', 'Clan Ammo ATM-9 ER (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869186, 986914, 'Right Torso', 'Clan Ammo ATM-9 HE (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869187, 986914, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869188, 986914, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869189, 986914, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869190, 986914, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869191, 986914, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869192, 986914, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869193, 986914, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869194, 986914, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869195, 986914, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869196, 986914, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869197, 986914, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869198, 986914, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869199, 986914, 'Center Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869200, 986914, 'Center Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869201, 986914, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869202, 986914, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869203, 986914, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869204, 986914, 'Head', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869205, 986914, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869206, 986914, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869207, 986914, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869208, 986914, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869209, 986914, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869210, 986914, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869211, 986914, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869212, 986914, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869213, 986914, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869214, 986914, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869215, 986914, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869216, 986914, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869217, 986914, 'Left Leg', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869218, 986914, 'Left Leg', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869219, 986914, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869220, 986914, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869221, 986914, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869222, 986914, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869223, 986914, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869224, 986914, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869225, 986914, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869226, 986914, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869227, 986914, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869228, 986914, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869229, 986914, 'Right Leg', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869230, 986914, 'Right Leg', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869231, 986914, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869232, 986914, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869233, 986914, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869234, 986914, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869235, 986914, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (9869236, 986914, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (986914, 986914, 'Barcella Alpha, Irece Alpha', 'Barcella, Irece', 'CHASSIS:Mynx Type Heavy');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (986914, 986914, 'A Nova Cat heavy OmniMech built to protect the Nova Cats spiritually and militarily.', "The basic components of this design, combined with its characteristics as an OmniMech, make it very simple to repair and leave room for the large amount of double heat sinks most variants carry. 13 ½ tons of standard armor make this ''Mech very difficult to kill.", 'The E configuration is close to the B variant, being equipped with a total of four new ATM 9s with two tons of ammo per launcher, and one Large Pulse Laser for pinpoint accuracy, finishing off any BattleMechs not destroyed by the multiple ATM launchers.', "After its defeat on Tukayyid, Khan Severen Leroux of Clan Nova Cat commissioned the Nova Cat OmniMech, meant to protect the Clan both militarily and spiritually. The 12 meter tall ''Mech is inspired by the Night Gyr created by Clan Jade Falcon.");