INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (602550, 'Puma', 'D', '2594', '35', 'Sniper', 'Biped Omnimech', 'Clan', '3010', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (602550, 602550, '210 XL (Clan) Engine(IS)', 'Clan Endo Steel', 'Standard', '10 Double', '6', '0');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (602550, 602550, 'Ferro-Fibrous(Clan)', 'LA Armor', '12');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (602550, 602550, 'Ferro-Fibrous(Clan)', 'RA Armor', '12');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (602550, 602550, 'Ferro-Fibrous(Clan)', 'LT Armor', '12');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (602550, 602550, 'Ferro-Fibrous(Clan)', 'RT Armor', '12');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (602550, 602550, 'Ferro-Fibrous(Clan)', 'CT Armor', '16');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (602550, 602550, 'Ferro-Fibrous(Clan)', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (602550, 602550, 'Ferro-Fibrous(Clan)', 'LL Armor', '14');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (602550, 602550, 'Ferro-Fibrous(Clan)', 'RL Armor', '14');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (602550, 602550, 'Ferro-Fibrous(Clan)', 'RTL Armor', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (602550, 602550, 'Ferro-Fibrous(Clan)', 'RTR Armor', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (602550, 602550, 'Ferro-Fibrous(Clan)', 'RTC Armor', '6');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (6025501, 602550, 'ER Large Laser', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (6025502, 602550, 'Ultra AC/5', 'Right Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (6025503, 602550, 'Streak SRM 2', 'Left Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (6025504, 602550, 'Streak SRM 2', 'Right Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (6025505, 602550, 'Flamer', 'Center Torso', None);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (6025501, 602550, 'low_profile');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025501, 602550, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025502, 602550, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025503, 602550, 'Left Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025504, 602550, 'Left Arm', 'Hand Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025505, 602550, 'Left Arm', 'CLERLargeLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025506, 602550, 'Left Arm', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025507, 602550, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025508, 602550, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025509, 602550, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025510, 602550, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025511, 602550, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025512, 602550, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025513, 602550, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025514, 602550, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025515, 602550, 'Right Arm', 'CLUltraAC5 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025516, 602550, 'Right Arm', 'CLUltraAC5 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025517, 602550, 'Right Arm', 'CLUltraAC5 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025518, 602550, 'Right Arm', 'Clan Ultra AC/5 Ammo (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025519, 602550, 'Right Arm', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025520, 602550, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025521, 602550, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025522, 602550, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025523, 602550, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025524, 602550, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025525, 602550, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025526, 602550, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025527, 602550, 'Left Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025528, 602550, 'Left Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025529, 602550, 'Left Torso', 'CLStreakSRM2 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025530, 602550, 'Left Torso', 'Clan Streak SRM 2 Ammo (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025531, 602550, 'Left Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025532, 602550, 'Left Torso', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025533, 602550, 'Left Torso', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025534, 602550, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025535, 602550, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025536, 602550, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025537, 602550, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025538, 602550, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025539, 602550, 'Right Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025540, 602550, 'Right Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025541, 602550, 'Right Torso', 'CLStreakSRM2 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025542, 602550, 'Right Torso', 'Clan Streak SRM 2 Ammo (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025543, 602550, 'Right Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025544, 602550, 'Right Torso', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025545, 602550, 'Right Torso', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025546, 602550, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025547, 602550, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025548, 602550, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025549, 602550, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025550, 602550, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025551, 602550, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025552, 602550, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025553, 602550, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025554, 602550, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025555, 602550, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025556, 602550, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025557, 602550, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025558, 602550, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025559, 602550, 'Center Torso', 'CLFlamer');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025560, 602550, 'Center Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025561, 602550, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025562, 602550, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025563, 602550, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025564, 602550, 'Head', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025565, 602550, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025566, 602550, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025567, 602550, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025568, 602550, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025569, 602550, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025570, 602550, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025571, 602550, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025572, 602550, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025573, 602550, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025574, 602550, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025575, 602550, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025576, 602550, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025577, 602550, 'Left Leg', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025578, 602550, 'Left Leg', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025579, 602550, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025580, 602550, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025581, 602550, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025582, 602550, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025583, 602550, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025584, 602550, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025585, 602550, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025586, 602550, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025587, 602550, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025588, 602550, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025589, 602550, 'Right Leg', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025590, 602550, 'Right Leg', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025591, 602550, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025592, 602550, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025593, 602550, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025594, 602550, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025595, 602550, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (6025596, 602550, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (602550, 602550, 'Sheridan LM-TA 8-10, W-7 Facilities,Wolf Clan Site 3, Assault Tech Industries', 'Sheridan LM-TA 8-10, W-7 Facilities,Wolf Clan Site 3, Assault Tech Industries', 'CHASSIS:Hooded Endo-Lite');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (602550, 602550, 'Codenamed Puma by Inner Sphere forces who first engaged it, the Adder is a light Clan OmniMech that serves as a direct or an indirect fire-support unit in most of its configurations. The Adder is capable of carrying a relatively heavy weapons payload that can surprise an unsuspecting enemy, even at extreme ranges.', "The Adder frees up as much weight as possible by using a weight-saving Endo Steel chassis and carrying a lightweight 210 XL Engine, which gives the 'Mech a top speed of 97.2 km/h. The Adder carries six tons of Ferro-Fibrous armor for protection from enemy fire. The effort to save weight has resulted in a 'Mech that dedicates almost half of its weight (some sixteen tons) to pod space. The Adder has a Flamer in a fixed mount which cannot be removed from the 'Mech.", "Another long range sniper configuration, the Adder D has an ER Large Laser and an Ultra Autocannon/5 for long range engagements, with a pair of Streak SRM-2 launchers to finish off any enemies who close with the 'Mech. This was one of the configurations designed as a result of intelligence from Wolf's Dragoons.", "The Adder was designed by Clan Star Adder in preparation for the invasion of the Inner Sphere. First produced in 3010, the formidable Adder was actually designed as an OmniMech capable of emulating the weapons configurations the Wolf's Dragoons reported as most common for medium Inner Sphere BattleMechs, the 'Mechs most frequently fielded by Successor State armies. Some of these configurations, including B, C, and D, are still used as of 3050. Despite producing such a formidable design, the Star Adders failed to maintain exclusive possession of the Adder; by 3045, the Adder had become common throughout the Clans. The development of the Adder was tied into the restructuring of the Star Adder's Kappa Galaxy to emulate an Inner Sphere force, to provide a training opponent for other Star Adder units. A number of the main configurations of the Adder were designed specifically for Kappa Galaxy, or were based on intelligence provided by Wolf's Dragoons.");