INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (387873, 'Raven', 'RVN-4L', '2666', '35', 'Scout', 'Biped', 'Inner Sphere', '3063', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (387873, 387873, '210 XL Engine', 'Standard', 'Standard', '10 Double', '6', '0');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (387873, 387873, 'Stealth Armor', 'LA Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (387873, 387873, 'Stealth Armor', 'RA Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (387873, 387873, 'Stealth Armor', 'LT Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (387873, 387873, 'Stealth Armor', 'RT Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (387873, 387873, 'Stealth Armor', 'CT Armor', '15');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (387873, 387873, 'Stealth Armor', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (387873, 387873, 'Stealth Armor', 'LL Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (387873, 387873, 'Stealth Armor', 'RL Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (387873, 387873, 'Stealth Armor', 'RTL Armor', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (387873, 387873, 'Stealth Armor', 'RTR Armor', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (387873, 387873, 'Stealth Armor', 'RTC Armor', '4');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3878731, 387873, '2 ISERMediumLaser', 'Right Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3878732, 387873, '1 ISSRM6', 'Right Torso', 'Ammo:15');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3878733, 387873, '1 ISBeagleActiveProbe', 'Center Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3878734, 387873, '1 ISTAG', 'Right Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3878735, 387873, '1 ISGuardianECM', 'Left Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3878736, 387873, '1 ISNarcBeacon', 'Left Arm', 'Ammo:12');
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (3878731, 387873, 'no_arms');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878731, 387873, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878732, 387873, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878733, 387873, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878734, 387873, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878735, 387873, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878736, 387873, 'Left Arm', 'ISNarcBeacon');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878737, 387873, 'Left Arm', 'ISNarcBeacon');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878738, 387873, 'Left Arm', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878739, 387873, 'Left Arm', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878740, 387873, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878741, 387873, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878742, 387873, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878743, 387873, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878744, 387873, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878745, 387873, 'Right Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878746, 387873, 'Right Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878747, 387873, 'Right Arm', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878748, 387873, 'Right Arm', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878749, 387873, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878750, 387873, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878751, 387873, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878752, 387873, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878753, 387873, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878754, 387873, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878755, 387873, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878756, 387873, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878757, 387873, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878758, 387873, 'Left Torso', 'ISGuardianECM');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878759, 387873, 'Left Torso', 'ISGuardianECM');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878760, 387873, 'Left Torso', 'ISSRM6 Ammo Narc-capable');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878761, 387873, 'Left Torso', 'ISNarc Pods');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878762, 387873, 'Left Torso', 'ISNarc Pods');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878763, 387873, 'Left Torso', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878764, 387873, 'Left Torso', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878765, 387873, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878766, 387873, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878767, 387873, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878768, 387873, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878769, 387873, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878770, 387873, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878771, 387873, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878772, 387873, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878773, 387873, 'Right Torso', 'ISSRM6');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878774, 387873, 'Right Torso', 'ISSRM6');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878775, 387873, 'Right Torso', 'ISTAG');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878776, 387873, 'Right Torso', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878777, 387873, 'Right Torso', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878778, 387873, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878779, 387873, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878780, 387873, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878781, 387873, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878782, 387873, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878783, 387873, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878784, 387873, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878785, 387873, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878786, 387873, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878787, 387873, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878788, 387873, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878789, 387873, 'Center Torso', 'ISBeagleActiveProbe');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878790, 387873, 'Center Torso', 'ISBeagleActiveProbe');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878791, 387873, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878792, 387873, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878793, 387873, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878794, 387873, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878795, 387873, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878796, 387873, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878797, 387873, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878798, 387873, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878799, 387873, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878800, 387873, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878801, 387873, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878802, 387873, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878803, 387873, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878804, 387873, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878805, 387873, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878806, 387873, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878807, 387873, 'Left Leg', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878808, 387873, 'Left Leg', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878809, 387873, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878810, 387873, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878811, 387873, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878812, 387873, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878813, 387873, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3878814, 387873, 'Left Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (387873, 387873, None, None, None);
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (387873, 387873, None, None, None, None);