INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (489144, 'Raven', 'RVN-4LC', '2667', '35', 'Scout', 'Biped', 'Inner Sphere', '3062', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (489144, 489144, '210 XL Engine', 'Standard', 'Standard', '10 Double', '6', '0');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (489144, 489144, 'Stealth', 'LA Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (489144, 489144, 'Stealth', 'RA Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (489144, 489144, 'Stealth', 'LT Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (489144, 489144, 'Stealth', 'RT Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (489144, 489144, 'Stealth', 'CT Armor', '15');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (489144, 489144, 'Stealth', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (489144, 489144, 'Stealth', 'LL Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (489144, 489144, 'Stealth', 'RL Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (489144, 489144, 'Stealth', 'RTL Armor', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (489144, 489144, 'Stealth', 'RTR Armor', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (489144, 489144, 'Stealth', 'RTC Armor', '4');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (4891441, 489144, '2 ISERMediumLaser', 'Right Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (4891442, 489144, '1 ISNarcBeacon', 'Left Arm', 'Ammo:12');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (4891443, 489144, '1 ISSRM6', 'Right Torso', 'Ammo:15');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (4891444, 489144, '1 ISTAG', 'Right Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (4891445, 489144, '1 ISGuardianECM', 'Left Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (4891446, 489144, '1 ISC3SlaveUnit', 'Center Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (4891447, 489144, '1 ISERSmallLaser', 'Center Torso', None);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (4891441, 489144, 'no_arms');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891441, 489144, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891442, 489144, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891443, 489144, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891444, 489144, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891445, 489144, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891446, 489144, 'Left Arm', 'ISNarcBeacon');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891447, 489144, 'Left Arm', 'ISNarcBeacon');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891448, 489144, 'Left Arm', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891449, 489144, 'Left Arm', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891450, 489144, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891451, 489144, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891452, 489144, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891453, 489144, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891454, 489144, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891455, 489144, 'Right Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891456, 489144, 'Right Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891457, 489144, 'Right Arm', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891458, 489144, 'Right Arm', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891459, 489144, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891460, 489144, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891461, 489144, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891462, 489144, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891463, 489144, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891464, 489144, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891465, 489144, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891466, 489144, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891467, 489144, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891468, 489144, 'Left Torso', 'ISGuardianECM');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891469, 489144, 'Left Torso', 'ISGuardianECM');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891470, 489144, 'Left Torso', 'ISSRM6 Ammo Narc-capable');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891471, 489144, 'Left Torso', 'ISNarc Pods');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891472, 489144, 'Left Torso', 'ISNarc Pods');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891473, 489144, 'Left Torso', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891474, 489144, 'Left Torso', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891475, 489144, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891476, 489144, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891477, 489144, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891478, 489144, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891479, 489144, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891480, 489144, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891481, 489144, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891482, 489144, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891483, 489144, 'Right Torso', 'ISSRM6');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891484, 489144, 'Right Torso', 'ISSRM6');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891485, 489144, 'Right Torso', 'ISTAG');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891486, 489144, 'Right Torso', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891487, 489144, 'Right Torso', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891488, 489144, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891489, 489144, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891490, 489144, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891491, 489144, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891492, 489144, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891493, 489144, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891494, 489144, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891495, 489144, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891496, 489144, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891497, 489144, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891498, 489144, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891499, 489144, 'Center Torso', 'ISC3SlaveUnit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891500, 489144, 'Center Torso', 'ISERSmallLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891501, 489144, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891502, 489144, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891503, 489144, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891504, 489144, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891505, 489144, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891506, 489144, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891507, 489144, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891508, 489144, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891509, 489144, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891510, 489144, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891511, 489144, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891512, 489144, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891513, 489144, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891514, 489144, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891515, 489144, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891516, 489144, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891517, 489144, 'Left Leg', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891518, 489144, 'Left Leg', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891519, 489144, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891520, 489144, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891521, 489144, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891522, 489144, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891523, 489144, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (4891524, 489144, 'Left Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (489144, 489144, None, None, None);
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (489144, 489144, None, None, None, None);