INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (775407, 'Raven', 'RVN-4L', '2666', '35', 'Scout', 'Biped', 'Inner Sphere', '3063', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (775407, 775407, '210 XL Engine', 'Standard', 'Standard', '10 Double', '6', '0');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (775407, 775407, 'Stealth Armor', 'LA Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (775407, 775407, 'Stealth Armor', 'RA Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (775407, 775407, 'Stealth Armor', 'LT Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (775407, 775407, 'Stealth Armor', 'RT Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (775407, 775407, 'Stealth Armor', 'CT Armor', '15');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (775407, 775407, 'Stealth Armor', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (775407, 775407, 'Stealth Armor', 'LL Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (775407, 775407, 'Stealth Armor', 'RL Armor', '10');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (775407, 775407, 'Stealth Armor', 'RTL Armor', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (775407, 775407, 'Stealth Armor', 'RTR Armor', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (775407, 775407, 'Stealth Armor', 'RTC Armor', '4');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7754071, 775407, '2 ISERMediumLaser', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7754072, 775407, '1 ISSRM6', 'Right Torso', Ammo:15);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7754073, 775407, '1 ISBeagleActiveProbe', 'Center Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7754074, 775407, '1 ISTAG', 'Right Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7754075, 775407, '1 ISGuardianECM', 'Left Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7754076, 775407, '1 ISNarcBeacon', 'Left Arm', Ammo:12);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (7754071, 775407, 'no_arms');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754071, 775407, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754072, 775407, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754073, 775407, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754074, 775407, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754075, 775407, 'Left Arm', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754076, 775407, 'Left Arm', 'ISNarcBeacon');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754077, 775407, 'Left Arm', 'ISNarcBeacon');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754078, 775407, 'Left Arm', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754079, 775407, 'Left Arm', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754080, 775407, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754081, 775407, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754082, 775407, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754083, 775407, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754084, 775407, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754085, 775407, 'Right Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754086, 775407, 'Right Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754087, 775407, 'Right Arm', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754088, 775407, 'Right Arm', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754089, 775407, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754090, 775407, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754091, 775407, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754092, 775407, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754093, 775407, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754094, 775407, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754095, 775407, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754096, 775407, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754097, 775407, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754098, 775407, 'Left Torso', 'ISGuardianECM');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754099, 775407, 'Left Torso', 'ISGuardianECM');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754100, 775407, 'Left Torso', 'ISSRM6 Ammo Narc-capable');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754101, 775407, 'Left Torso', 'ISNarc Pods');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754102, 775407, 'Left Torso', 'ISNarc Pods');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754103, 775407, 'Left Torso', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754104, 775407, 'Left Torso', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754105, 775407, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754106, 775407, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754107, 775407, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754108, 775407, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754109, 775407, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754110, 775407, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754111, 775407, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754112, 775407, 'Right Torso', 'ISDouble Heat Sink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754113, 775407, 'Right Torso', 'ISSRM6');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754114, 775407, 'Right Torso', 'ISSRM6');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754115, 775407, 'Right Torso', 'ISTAG');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754116, 775407, 'Right Torso', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754117, 775407, 'Right Torso', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754118, 775407, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754119, 775407, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754120, 775407, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754121, 775407, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754122, 775407, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754123, 775407, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754124, 775407, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754125, 775407, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754126, 775407, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754127, 775407, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754128, 775407, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754129, 775407, 'Center Torso', 'ISBeagleActiveProbe');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754130, 775407, 'Center Torso', 'ISBeagleActiveProbe');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754131, 775407, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754132, 775407, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754133, 775407, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754134, 775407, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754135, 775407, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754136, 775407, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754137, 775407, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754138, 775407, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754139, 775407, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754140, 775407, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754141, 775407, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754142, 775407, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754143, 775407, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754144, 775407, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754145, 775407, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754146, 775407, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754147, 775407, 'Left Leg', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754148, 775407, 'Left Leg', 'Stealth Armor');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754149, 775407, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754150, 775407, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754151, 775407, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754152, 775407, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754153, 775407, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7754154, 775407, 'Left Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (775407, 775407, None, None, None);
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (775407, 775407, None, None, None, None);