INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (139010, 'Sha Yu', 'SYU-4B', '5027', None, 'Striker', 'Biped', None, None, None, None);
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (139010, 139010, None, None, None, None, None, None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1390101, 139010, 'Medium Pulse Laser', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1390102, 139010, 'Medium Pulse Laser', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1390103, 139010, 'ER Medium Laser', 'Left Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1390104, 139010, 'ER Medium Laser', 'Right Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1390105, 139010, 'LRM 5', 'Right Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1390106, 139010, 'Medium Pulse Laser', 'Head', NULL);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (1390101, 139010, 'imp_com');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390101, 139010, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390102, 139010, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390103, 139010, 'Left Arm', 'ISMediumPulseLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390104, 139010, 'Left Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390105, 139010, 'Left Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390106, 139010, 'Left Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390107, 139010, 'Left Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390108, 139010, 'Left Arm', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390109, 139010, 'Left Arm', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390110, 139010, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390111, 139010, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390112, 139010, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390113, 139010, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390114, 139010, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390115, 139010, 'Right Arm', 'ISMediumPulseLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390116, 139010, 'Right Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390117, 139010, 'Right Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390118, 139010, 'Right Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390119, 139010, 'Right Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390120, 139010, 'Right Arm', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390121, 139010, 'Right Arm', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390122, 139010, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390123, 139010, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390124, 139010, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390125, 139010, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390126, 139010, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390127, 139010, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390128, 139010, 'Left Torso', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390129, 139010, 'Left Torso', 'ISC3SlaveUnit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390130, 139010, 'Left Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390131, 139010, 'Left Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390132, 139010, 'Left Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390133, 139010, 'Left Torso', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390134, 139010, 'Left Torso', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390135, 139010, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390136, 139010, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390137, 139010, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390138, 139010, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390139, 139010, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390140, 139010, 'Right Torso', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390141, 139010, 'Right Torso', 'LRM 5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390142, 139010, 'Right Torso', 'IS Ammo LRM-5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390143, 139010, 'Right Torso', 'IS Ammo LRM-5');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390144, 139010, 'Right Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390145, 139010, 'Right Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390146, 139010, 'Right Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390147, 139010, 'Right Torso', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390148, 139010, 'Right Torso', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390149, 139010, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390150, 139010, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390151, 139010, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390152, 139010, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390153, 139010, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390154, 139010, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390155, 139010, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390156, 139010, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390157, 139010, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390158, 139010, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390159, 139010, 'Center Torso', 'ISGuardianECMSuite');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390160, 139010, 'Center Torso', 'ISGuardianECMSuite');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390161, 139010, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390162, 139010, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390163, 139010, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390164, 139010, 'Head', 'ISMediumPulseLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390165, 139010, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390166, 139010, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390167, 139010, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390168, 139010, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390169, 139010, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390170, 139010, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390171, 139010, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390172, 139010, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390173, 139010, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390174, 139010, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390175, 139010, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390176, 139010, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390177, 139010, 'Left Leg', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390178, 139010, 'Left Leg', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390179, 139010, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390180, 139010, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390181, 139010, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390182, 139010, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390183, 139010, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1390184, 139010, 'Left Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (139010, 139010, None, None, None);
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (139010, 139010, None, None, None, None);