INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (837456, 'Sha Yu', 'SYU-2B', '5026', None, 'Sniper', 'Biped', None, None, None, None);
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (837456, 837456, None, None, None, None, None, None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (8374561, 837456, 'ER Large Laser', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (8374562, 837456, 'ER Large Laser', 'Right Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (8374563, 837456, 'ER Medium Laser', 'Left Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (8374564, 837456, 'ER Medium Laser', 'Right Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (8374565, 837456, 'TAG', 'Head', None);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (8374561, 837456, 'imp_com');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374561, 837456, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374562, 837456, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374563, 837456, 'Left Arm', 'ISERLargeLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374564, 837456, 'Left Arm', 'ISERLargeLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374565, 837456, 'Left Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374566, 837456, 'Left Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374567, 837456, 'Left Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374568, 837456, 'Left Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374569, 837456, 'Left Arm', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374570, 837456, 'Left Arm', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374571, 837456, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374572, 837456, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374573, 837456, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374574, 837456, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374575, 837456, 'Right Arm', 'ISERLargeLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374576, 837456, 'Right Arm', 'ISERLargeLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374577, 837456, 'Right Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374578, 837456, 'Right Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374579, 837456, 'Right Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374580, 837456, 'Right Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374581, 837456, 'Right Arm', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374582, 837456, 'Right Arm', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374583, 837456, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374584, 837456, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374585, 837456, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374586, 837456, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374587, 837456, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374588, 837456, 'Left Torso', 'ISDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374589, 837456, 'Left Torso', 'ISDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374590, 837456, 'Left Torso', 'ISDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374591, 837456, 'Left Torso', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374592, 837456, 'Left Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374593, 837456, 'Left Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374594, 837456, 'Left Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374595, 837456, 'Left Torso', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374596, 837456, 'Left Torso', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374597, 837456, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374598, 837456, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374599, 837456, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374600, 837456, 'Right Torso', 'ISDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374601, 837456, 'Right Torso', 'ISDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374602, 837456, 'Right Torso', 'ISDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374603, 837456, 'Right Torso', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374604, 837456, 'Right Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374605, 837456, 'Right Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374606, 837456, 'Right Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374607, 837456, 'Right Torso', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374608, 837456, 'Right Torso', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374609, 837456, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374610, 837456, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374611, 837456, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374612, 837456, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374613, 837456, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374614, 837456, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374615, 837456, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374616, 837456, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374617, 837456, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374618, 837456, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374619, 837456, 'Center Torso', 'ISGuardianECMSuite');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374620, 837456, 'Center Torso', 'ISGuardianECMSuite');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374621, 837456, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374622, 837456, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374623, 837456, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374624, 837456, 'Head', 'ISTAG');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374625, 837456, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374626, 837456, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374627, 837456, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374628, 837456, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374629, 837456, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374630, 837456, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374631, 837456, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374632, 837456, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374633, 837456, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374634, 837456, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374635, 837456, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374636, 837456, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374637, 837456, 'Left Leg', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374638, 837456, 'Left Leg', 'IS Stealth');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374639, 837456, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374640, 837456, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374641, 837456, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374642, 837456, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374643, 837456, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (8374644, 837456, 'Left Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (837456, 837456, None, None, None);
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (837456, 837456, None, None, None, None);