INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (764446, 'Star Adder', 'B', '400', '90', 'Missile Boat', 'Biped Omnimech', 'Clan', '3060', '2', 'TRO: 3060');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (764446, 764446, '360 XL (Clan) Engine(IS)', 'Clan Endo Steel', 'Standard', '16 Double', '4', '0');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (764446, 764446, 'Standard(Clan)', 'LA Armor', '28');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (764446, 764446, 'Standard(Clan)', 'RA Armor', '28');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (764446, 764446, 'Standard(Clan)', 'LT Armor', '24');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (764446, 764446, 'Standard(Clan)', 'RT Armor', '24');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (764446, 764446, 'Standard(Clan)', 'CT Armor', '40');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (764446, 764446, 'Standard(Clan)', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (764446, 764446, 'Standard(Clan)', 'LL Armor', '34');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (764446, 764446, 'Standard(Clan)', 'RL Armor', '34');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (764446, 764446, 'Standard(Clan)', 'RTL Armor', '11');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (764446, 764446, 'Standard(Clan)', 'RTR Armor', '11');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (764446, 764446, 'Standard(Clan)', 'RTC Armor', '13');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7644461, 764446, 'LRM 20', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7644462, 764446, 'LRM 20', 'Right Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7644463, 764446, 'Medium Pulse Laser', 'Left Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7644464, 764446, 'Medium Pulse Laser', 'Left Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7644465, 764446, 'Medium Pulse Laser', 'Left Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7644466, 764446, 'Medium Pulse Laser', 'Left Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (7644467, 764446, 'Gauss Rifle', 'Right Torso', None);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (7644461, 764446, 'rugged_1');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644461, 764446, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644462, 764446, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644463, 764446, 'Left Arm', 'CLLRM20 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644464, 764446, 'Left Arm', 'CLLRM20 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644465, 764446, 'Left Arm', 'CLLRM20 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644466, 764446, 'Left Arm', 'CLLRM20 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644467, 764446, 'Left Arm', 'CLArtemisIV (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644468, 764446, 'Left Arm', 'Clan Ammo LRM-20 (Clan) Artemis-capable (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644469, 764446, 'Left Arm', 'Clan Ammo LRM-20 (Clan) Artemis-capable (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644470, 764446, 'Left Arm', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644471, 764446, 'Left Arm', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644472, 764446, 'Left Arm', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644473, 764446, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644474, 764446, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644475, 764446, 'Right Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644476, 764446, 'Right Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644477, 764446, 'Right Arm', 'CLLRM20 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644478, 764446, 'Right Arm', 'CLLRM20 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644479, 764446, 'Right Arm', 'CLLRM20 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644480, 764446, 'Right Arm', 'CLLRM20 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644481, 764446, 'Right Arm', 'CLArtemisIV (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644482, 764446, 'Right Arm', 'Clan Ammo LRM-20 (Clan) Artemis-capable (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644483, 764446, 'Right Arm', 'Clan Ammo LRM-20 (Clan) Artemis-capable (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644484, 764446, 'Right Arm', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644485, 764446, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644486, 764446, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644487, 764446, 'Left Torso', 'CLMediumPulseLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644488, 764446, 'Left Torso', 'CLMediumPulseLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644489, 764446, 'Left Torso', 'CLMediumPulseLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644490, 764446, 'Left Torso', 'CLMediumPulseLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644491, 764446, 'Left Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644492, 764446, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644493, 764446, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644494, 764446, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644495, 764446, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644496, 764446, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644497, 764446, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644498, 764446, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644499, 764446, 'Right Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644500, 764446, 'Right Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644501, 764446, 'Right Torso', 'CLGaussRifle (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644502, 764446, 'Right Torso', 'CLGaussRifle (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644503, 764446, 'Right Torso', 'CLGaussRifle (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644504, 764446, 'Right Torso', 'CLGaussRifle (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644505, 764446, 'Right Torso', 'CLGaussRifle (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644506, 764446, 'Right Torso', 'CLGaussRifle (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644507, 764446, 'Right Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644508, 764446, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644509, 764446, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644510, 764446, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644511, 764446, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644512, 764446, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644513, 764446, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644514, 764446, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644515, 764446, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644516, 764446, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644517, 764446, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644518, 764446, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644519, 764446, 'Center Torso', 'CLECMSuite (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644520, 764446, 'Center Torso', 'Clan Gauss Ammo (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644521, 764446, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644522, 764446, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644523, 764446, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644524, 764446, 'Head', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644525, 764446, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644526, 764446, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644527, 764446, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644528, 764446, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644529, 764446, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644530, 764446, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644531, 764446, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644532, 764446, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644533, 764446, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644534, 764446, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644535, 764446, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644536, 764446, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644537, 764446, 'Left Leg', 'Clan Gauss Ammo (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644538, 764446, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644539, 764446, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644540, 764446, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644541, 764446, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644542, 764446, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644543, 764446, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644544, 764446, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644545, 764446, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644546, 764446, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644547, 764446, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644548, 764446, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644549, 764446, 'Right Leg', 'Clan Gauss Ammo (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644550, 764446, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644551, 764446, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644552, 764446, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644553, 764446, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644554, 764446, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644555, 764446, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (7644556, 764446, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (764446, 764446, 'Sheridan LM-TA 8-10', 'Sheridan', 'CHASSIS:Type MAES-90 Light');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (764446, 764446, "One of the first 'Mechs to field the breakthrough Heavy Laser technology, the Blood Asp proves to be an offensive powerhouse. Delivering incredible damage at all ranges, the Blood Asp makes short work of any enemy regardless of size.", "Based on the Kingfisher, the Blood Asp adds an XL engine, but space constraints forced the replacement of the Kingfisher's ferro-fibrous armor with standard plate. The Blood Asp incorporates sixteen tons of this armor and fourteen double heat sinks in the base chassis.", 'The second alternate configuration is a fire-support design that uses a Gauss rifle and a pair of LRM-20s with Artemis IV Fire Control Systems. In case an enemy unit gets close, it mounts four Medium Pulse Lasers and an ECM Suite. Two additional heat sinks ensure this design stays cool.', 'Created by Clan Star Adder as an insult to their enemies, Clan Blood Spirit, the Blood Asp has a large amount of available pod space for its size.');