INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (326662, 'Star Adder', 'Prime', '406', None, 'Brawler', 'Biped Omnimech', None, None, None, None);
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (326662, 326662, None, None, None, None, None, None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3266621, 326662, 'Heavy Medium Laser', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3266622, 326662, 'Heavy Medium Laser', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3266623, 326662, 'Medium Pulse Laser', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3266624, 326662, 'Heavy Medium Laser', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3266625, 326662, 'Heavy Medium Laser', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3266626, 326662, 'Medium Pulse Laser', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3266627, 326662, 'Gauss Rifle', 'Left Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3266628, 326662, 'Gauss Rifle', 'Right Torso', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3266629, 326662, 'Streak SRM 6', 'Center Torso', NULL);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (3266621, 326662, 'rugged_1');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266621, 326662, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266622, 326662, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266623, 326662, 'Left Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266624, 326662, 'Left Arm', 'CLHeavyMediumLaser (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266625, 326662, 'Left Arm', 'CLHeavyMediumLaser (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266626, 326662, 'Left Arm', 'CLHeavyMediumLaser (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266627, 326662, 'Left Arm', 'CLHeavyMediumLaser (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266628, 326662, 'Left Arm', 'CLMediumPulseLaser (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266629, 326662, 'Left Arm', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266630, 326662, 'Left Arm', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266631, 326662, 'Left Arm', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266632, 326662, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266633, 326662, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266634, 326662, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266635, 326662, 'Right Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266636, 326662, 'Right Arm', 'CLDoubleHeatSink (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266637, 326662, 'Right Arm', 'CLDoubleHeatSink (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266638, 326662, 'Right Arm', 'CLHeavyMediumLaser (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266639, 326662, 'Right Arm', 'CLHeavyMediumLaser (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266640, 326662, 'Right Arm', 'CLHeavyMediumLaser (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266641, 326662, 'Right Arm', 'CLHeavyMediumLaser (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266642, 326662, 'Right Arm', 'CLMediumPulseLaser (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266643, 326662, 'Right Arm', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266644, 326662, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266645, 326662, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266646, 326662, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266647, 326662, 'Left Torso', 'CLDoubleHeatSink (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266648, 326662, 'Left Torso', 'CLDoubleHeatSink (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266649, 326662, 'Left Torso', 'CLGaussRifle (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266650, 326662, 'Left Torso', 'CLGaussRifle (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266651, 326662, 'Left Torso', 'CLGaussRifle (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266652, 326662, 'Left Torso', 'CLGaussRifle (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266653, 326662, 'Left Torso', 'CLGaussRifle (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266654, 326662, 'Left Torso', 'CLGaussRifle (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266655, 326662, 'Left Torso', 'Clan Gauss Ammo (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266656, 326662, 'Left Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266657, 326662, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266658, 326662, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266659, 326662, 'Right Torso', 'CLGaussRifle (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266660, 326662, 'Right Torso', 'CLGaussRifle (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266661, 326662, 'Right Torso', 'CLGaussRifle (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266662, 326662, 'Right Torso', 'CLGaussRifle (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266663, 326662, 'Right Torso', 'CLGaussRifle (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266664, 326662, 'Right Torso', 'CLGaussRifle (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266665, 326662, 'Right Torso', 'Clan Gauss Ammo (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266666, 326662, 'Right Torso', 'Clan Streak SRM 6 Ammo (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266667, 326662, 'Right Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266668, 326662, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266669, 326662, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266670, 326662, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266671, 326662, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266672, 326662, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266673, 326662, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266674, 326662, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266675, 326662, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266676, 326662, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266677, 326662, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266678, 326662, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266679, 326662, 'Center Torso', 'CLStreakSRM6 (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266680, 326662, 'Center Torso', 'CLStreakSRM6 (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266681, 326662, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266682, 326662, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266683, 326662, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266684, 326662, 'Head', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266685, 326662, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266686, 326662, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266687, 326662, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266688, 326662, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266689, 326662, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266690, 326662, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266691, 326662, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266692, 326662, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266693, 326662, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266694, 326662, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266695, 326662, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266696, 326662, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266697, 326662, 'Left Leg', 'CLDoubleHeatSink (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266698, 326662, 'Left Leg', 'CLDoubleHeatSink (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266699, 326662, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266700, 326662, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266701, 326662, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266702, 326662, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266703, 326662, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266704, 326662, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266705, 326662, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266706, 326662, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266707, 326662, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266708, 326662, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266709, 326662, 'Right Leg', 'CLDoubleHeatSink (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266710, 326662, 'Right Leg', 'CLDoubleHeatSink (OMNIPOD)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266711, 326662, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266712, 326662, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266713, 326662, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266714, 326662, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266715, 326662, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3266716, 326662, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (326662, 326662, 'Sheridan LM-TA 8-10', 'Sheridan', 'CHASSIS:Type MAES-90 Light');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (326662, 326662, "One of the first ''Mechs to field the breakthrough Heavy Laser technology, the Blood Asp proves to be an offensive powerhouse. Delivering incredible damage at all ranges, the Blood Asp makes short work of any enemy regardless of size.", "Based on the Kingfisher, the Blood Asp adds an XL engine, but space constraints forced the replacement of the Kingfisher''s ferro-fibrous armor with standard plate. The Blood Asp incorporates sixteen tons of this armor and fourteen double heat sinks in the base chassis.", "The Blood Asp''s primary weapons are a pair of Gauss rifles that can strip off nearly a ton of armor at the range of six hundred and sixty meters, though they do not have a lot of ammunition, so MechWarriors must be sparing with their shots. These are backed up by four Heavy Medium Lasers, a pair of Medium Pulse Lasers, and a Streak SRM-6 for close-range work. To aid in heat dissipation, the primary configuration incorporates four additional heat sinks.", 'Created by Clan Star Adder as an insult to their enemies, Clan Blood Spirit, the Blood Asp has a large amount of available pod space for its size.');