INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (371334, 'Star Adder', 'A', '399', '90', 'Brawler', 'Biped Omnimech', 'Clan', '3060', '2', 'TRO: 3060');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (371334, 371334, '360 XL (Clan) Engine(IS)', 'Clan Endo Steel', 'Standard', '25 Double', '4', '3');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (371334, 371334, 'Standard(Clan)', 'LA Armor', '28');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (371334, 371334, 'Standard(Clan)', 'RA Armor', '28');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (371334, 371334, 'Standard(Clan)', 'LT Armor', '24');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (371334, 371334, 'Standard(Clan)', 'RT Armor', '24');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (371334, 371334, 'Standard(Clan)', 'CT Armor', '40');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (371334, 371334, 'Standard(Clan)', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (371334, 371334, 'Standard(Clan)', 'LL Armor', '34');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (371334, 371334, 'Standard(Clan)', 'RL Armor', '34');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (371334, 371334, 'Standard(Clan)', 'RTL Armor', '11');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (371334, 371334, 'Standard(Clan)', 'RTR Armor', '11');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (371334, 371334, 'Standard(Clan)', 'RTC Armor', '13');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3713341, 371334, 'Heavy Large Laser', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3713342, 371334, 'ER PPC', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3713343, 371334, 'Heavy Large Laser', 'Right Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3713344, 371334, 'ER PPC', 'Right Arm', None);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (3713341, 371334, 'rugged_1');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713341, 371334, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713342, 371334, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713343, 371334, 'Left Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713344, 371334, 'Left Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713345, 371334, 'Left Arm', 'CLHeavyLargeLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713346, 371334, 'Left Arm', 'CLHeavyLargeLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713347, 371334, 'Left Arm', 'CLHeavyLargeLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713348, 371334, 'Left Arm', 'CLERPPC (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713349, 371334, 'Left Arm', 'CLERPPC (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713350, 371334, 'Left Arm', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713351, 371334, 'Left Arm', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713352, 371334, 'Left Arm', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713353, 371334, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713354, 371334, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713355, 371334, 'Right Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713356, 371334, 'Right Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713357, 371334, 'Right Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713358, 371334, 'Right Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713359, 371334, 'Right Arm', 'CLHeavyLargeLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713360, 371334, 'Right Arm', 'CLHeavyLargeLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713361, 371334, 'Right Arm', 'CLHeavyLargeLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713362, 371334, 'Right Arm', 'CLERPPC (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713363, 371334, 'Right Arm', 'CLERPPC (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713364, 371334, 'Right Arm', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713365, 371334, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713366, 371334, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713367, 371334, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713368, 371334, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713369, 371334, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713370, 371334, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713371, 371334, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713372, 371334, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713373, 371334, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713374, 371334, 'Left Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713375, 371334, 'Left Torso', 'Jump Jet (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713376, 371334, 'Left Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713377, 371334, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713378, 371334, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713379, 371334, 'Right Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713380, 371334, 'Right Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713381, 371334, 'Right Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713382, 371334, 'Right Torso', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713383, 371334, 'Right Torso', 'Jump Jet (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713384, 371334, 'Right Torso', 'CLTargeting Computer (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713385, 371334, 'Right Torso', 'CLTargeting Computer (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713386, 371334, 'Right Torso', 'CLTargeting Computer (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713387, 371334, 'Right Torso', 'CLTargeting Computer (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713388, 371334, 'Right Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713389, 371334, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713390, 371334, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713391, 371334, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713392, 371334, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713393, 371334, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713394, 371334, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713395, 371334, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713396, 371334, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713397, 371334, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713398, 371334, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713399, 371334, 'Center Torso', 'Jump Jet (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713400, 371334, 'Center Torso', 'CLECMSuite (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713401, 371334, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713402, 371334, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713403, 371334, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713404, 371334, 'Head', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713405, 371334, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713406, 371334, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713407, 371334, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713408, 371334, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713409, 371334, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713410, 371334, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713411, 371334, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713412, 371334, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713413, 371334, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713414, 371334, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713415, 371334, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713416, 371334, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713417, 371334, 'Left Leg', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713418, 371334, 'Left Leg', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713419, 371334, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713420, 371334, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713421, 371334, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713422, 371334, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713423, 371334, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713424, 371334, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713425, 371334, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713426, 371334, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713427, 371334, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713428, 371334, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713429, 371334, 'Right Leg', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713430, 371334, 'Right Leg', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713431, 371334, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713432, 371334, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713433, 371334, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713434, 371334, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713435, 371334, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3713436, 371334, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (371334, 371334, 'Sheridan LM-TA 8-10', 'Sheridan', 'CHASSIS:Type MAES-90 Light');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (371334, 371334, "One of the first 'Mechs to field the breakthrough Heavy Laser technology, the Blood Asp proves to be an offensive powerhouse. Delivering incredible damage at all ranges, the Blood Asp makes short work of any enemy regardless of size.", "Based on the Kingfisher, the Blood Asp adds an XL engine, but space constraints forced the replacement of the Kingfisher's ferro-fibrous armor with standard plate. The Blood Asp incorporates sixteen tons of this armor and fourteen double heat sinks in the base chassis.", 'This configuration is built for assault. It uses an advanced Targeting Computer to guide a pair of ER PPCs and two Heavy Large Lasers. Eleven additional heat sinks fail to keep this configuration cool, especially with the addition of enough jump jets to leap ninety meters at a time. It also incorporates an ECM Suite to protect itself from enemy electronics.', 'Created by Clan Star Adder as an insult to their enemies, Clan Blood Spirit, the Blood Asp has a large amount of available pod space for its size.');