INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (300084, 'Uller', 'E', '3344', '30', 'Striker', 'Biped Omnimech', 'Clan', '3054', '2', 'TRO: 3050');
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (300084, 300084, '180 XL (Clan) Engine(IS)', 'Clan Endo Steel', 'Standard', '12 Double', '6', '6');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300084, 300084, 'Ferro-Fibrous(Clan)', 'LA Armor', '7');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300084, 300084, 'Ferro-Fibrous(Clan)', 'RA Armor', '7');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300084, 300084, 'Ferro-Fibrous(Clan)', 'LT Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300084, 300084, 'Ferro-Fibrous(Clan)', 'RT Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300084, 300084, 'Ferro-Fibrous(Clan)', 'CT Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300084, 300084, 'Ferro-Fibrous(Clan)', 'HD Armor', '9');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300084, 300084, 'Ferro-Fibrous(Clan)', 'LL Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300084, 300084, 'Ferro-Fibrous(Clan)', 'RL Armor', '8');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300084, 300084, 'Ferro-Fibrous(Clan)', 'RTL Armor', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300084, 300084, 'Ferro-Fibrous(Clan)', 'RTR Armor', '4');
INSERT INTO Armor (armor_id, chassis_id, armor_type, location, armor_value) VALUES (300084, 300084, 'Ferro-Fibrous(Clan)', 'RTC Armor', '4');
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3000841, 300084, 'ATM 3', 'Left Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3000842, 300084, 'ER PPC', 'Right Arm', NULL);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (3000843, 300084, 'ER Small Laser', 'Right Arm', NULL);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (3000841, 300084, 'low_profile');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000841, 300084, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000842, 300084, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000843, 300084, 'Left Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000844, 300084, 'Left Arm', 'Hand Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000845, 300084, 'Left Arm', 'CLATM3 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000846, 300084, 'Left Arm', 'CLATM3 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000847, 300084, 'Left Arm', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000848, 300084, 'Left Arm', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000849, 300084, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000850, 300084, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000851, 300084, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000852, 300084, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000853, 300084, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000854, 300084, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000855, 300084, 'Right Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000856, 300084, 'Right Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000857, 300084, 'Right Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000858, 300084, 'Right Arm', 'CLDoubleHeatSink (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000859, 300084, 'Right Arm', 'CLERPPC (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000860, 300084, 'Right Arm', 'CLERPPC (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000861, 300084, 'Right Arm', 'CLERSmallLaser (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000862, 300084, 'Right Arm', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000863, 300084, 'Right Arm', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000864, 300084, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000865, 300084, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000866, 300084, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000867, 300084, 'Left Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000868, 300084, 'Left Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000869, 300084, 'Left Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000870, 300084, 'Left Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000871, 300084, 'Left Torso', 'Jump Jet (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000872, 300084, 'Left Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000873, 300084, 'Left Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000874, 300084, 'Left Torso', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000875, 300084, 'Left Torso', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000876, 300084, 'Left Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000877, 300084, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000878, 300084, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000879, 300084, 'Right Torso', 'Jump Jet (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000880, 300084, 'Right Torso', 'Clan Ammo ATM-3 (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000881, 300084, 'Right Torso', 'Clan Ammo ATM-3 ER (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000882, 300084, 'Right Torso', 'Clan Ammo ATM-3 HE (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000883, 300084, 'Right Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000884, 300084, 'Right Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000885, 300084, 'Right Torso', 'Clan Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000886, 300084, 'Right Torso', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000887, 300084, 'Right Torso', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000888, 300084, 'Right Torso', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000889, 300084, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000890, 300084, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000891, 300084, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000892, 300084, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000893, 300084, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000894, 300084, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000895, 300084, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000896, 300084, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000897, 300084, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000898, 300084, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000899, 300084, 'Center Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000900, 300084, 'Center Torso', 'CLDoubleHeatSink');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000901, 300084, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000902, 300084, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000903, 300084, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000904, 300084, 'Head', 'Clan Ferro-Fibrous');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000905, 300084, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000906, 300084, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000907, 300084, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000908, 300084, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000909, 300084, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000910, 300084, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000911, 300084, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000912, 300084, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000913, 300084, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000914, 300084, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000915, 300084, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000916, 300084, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000917, 300084, 'Left Leg', 'Jump Jet (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000918, 300084, 'Left Leg', 'Jump Jet (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000919, 300084, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000920, 300084, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000921, 300084, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000922, 300084, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000923, 300084, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000924, 300084, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000925, 300084, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000926, 300084, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000927, 300084, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000928, 300084, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000929, 300084, 'Right Leg', 'Jump Jet (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000930, 300084, 'Right Leg', 'Jump Jet (omnipod)');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000931, 300084, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000932, 300084, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000933, 300084, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000934, 300084, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000935, 300084, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (3000936, 300084, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (300084, 300084, 'Babylon MechWorks V (Cloud Cobra),Production Line Gamma 2 (Snow Raven),Ironhold Plant 9 (Jade Falcon),Snow Raven Industrial Complex Beta', 'Babylon, Lum, Ironhold, Mitchella', 'CHASSIS:Process 12 Endo-steel');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (300084, 300084, 'The Kit Fox is a light Clan OmniMech with long-range combat as a primary focus, earning it the Inner Sphere codename of Uller, after the Norse god of archery.', "The Kit Fox E sports the new Advanced Tactical Missile system, mounting an ATM-3 rack, which can fire ammunition specifically designed for maximum effectiveness at a certain range, causing more damage at shorter ranges. Six added Jump Jets, allowing for a jump capacity of 180 meters, provide the Kit Fox E with additional mobility, allowing it to better exploit the ATM system, and an ER PPC provides the high firepower common to the ''Mech.", 'In its primary configuration, the Kit Fox mounts an ER Large Laser and Small Pulse Laser on the left arm as its primary source of firepower. These are supplemented by an LB 5-X Autocannon for tactical flexibility and a Streak SRM-4 rack for close range combat.', 'The Kit Fox was another light OmniMech designed by Clan Cloud Cobra, and was first produced in 2890 with the aid of new resources coming from the Tanite Worlds. Rather than emphasize speed, the Kit Fox emphasizes armor and firepower, complementary to the role of the Fire Moth. Clan Jade Falcon Khan Bret Malthus took note of the new design after a string of Cloud Cobra victories, and issued a batchall to the Cobras, a challenge the Jade Falcons only very narrowly won. Clan Snow Raven also produces the Kit Fox, which they acquired by trade. All other Clans field the Kit Fox as isorla, except Clan Blood Spirit, who was gifted the Kit Fox by the generous (or Machiavellian?) Ravens.');