INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (223749, 'Uziel', 'UZL-2S', '5331', None, 'Striker', 'Biped', None, None, None, None);
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (223749, 223749, None, None, None, None, None, None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2237491, 223749, 'PPC', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2237492, 223749, 'PPC', 'Right Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2237493, 223749, 'Machine Gun', 'Left Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2237494, 223749, 'Machine Gun', 'Right Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (2237495, 223749, 'SRM 6', 'Center Torso', None);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (2237491, 223749, 'cowl');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237491, 223749, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237492, 223749, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237493, 223749, 'Left Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237494, 223749, 'Left Arm', 'PPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237495, 223749, 'Left Arm', 'PPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237496, 223749, 'Left Arm', 'PPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237497, 223749, 'Left Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237498, 223749, 'Left Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237499, 223749, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237500, 223749, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237501, 223749, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237502, 223749, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237503, 223749, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237504, 223749, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237505, 223749, 'Right Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237506, 223749, 'Right Arm', 'PPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237507, 223749, 'Right Arm', 'PPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237508, 223749, 'Right Arm', 'PPC');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237509, 223749, 'Right Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237510, 223749, 'Right Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237511, 223749, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237512, 223749, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237513, 223749, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237514, 223749, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237515, 223749, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237516, 223749, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237517, 223749, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237518, 223749, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237519, 223749, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237520, 223749, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237521, 223749, 'Left Torso', 'Machine Gun');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237522, 223749, 'Left Torso', 'IS Machine Gun Ammo - Half');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237523, 223749, 'Left Torso', 'IS Ammo SRM-6');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237524, 223749, 'Left Torso', 'BeagleActiveProbe');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237525, 223749, 'Left Torso', 'BeagleActiveProbe');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237526, 223749, 'Left Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237527, 223749, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237528, 223749, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237529, 223749, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237530, 223749, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237531, 223749, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237532, 223749, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237533, 223749, 'Right Torso', 'Machine Gun');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237534, 223749, 'Right Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237535, 223749, 'Right Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237536, 223749, 'Right Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237537, 223749, 'Right Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237538, 223749, 'Right Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237539, 223749, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237540, 223749, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237541, 223749, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237542, 223749, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237543, 223749, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237544, 223749, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237545, 223749, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237546, 223749, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237547, 223749, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237548, 223749, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237549, 223749, 'Center Torso', 'SRM 6');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237550, 223749, 'Center Torso', 'SRM 6');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237551, 223749, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237552, 223749, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237553, 223749, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237554, 223749, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237555, 223749, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237556, 223749, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237557, 223749, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237558, 223749, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237559, 223749, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237560, 223749, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237561, 223749, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237562, 223749, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237563, 223749, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237564, 223749, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237565, 223749, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237566, 223749, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237567, 223749, 'Left Leg', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237568, 223749, 'Left Leg', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237569, 223749, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237570, 223749, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237571, 223749, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237572, 223749, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237573, 223749, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237574, 223749, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237575, 223749, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237576, 223749, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237577, 223749, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237578, 223749, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237579, 223749, 'Right Leg', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237580, 223749, 'Right Leg', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237581, 223749, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237582, 223749, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237583, 223749, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237584, 223749, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237585, 223749, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (2237586, 223749, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (223749, 223749, 'Defiance Industries', 'Furillo', 'CHASSIS:Foundation E50 Endo Steel');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (223749, 223749, "Built at Defiance Industries' Furillo plant, the Uziel is an effective medium 'Mech that is looked down upon by the LAAF simply because it is produced on Furillo and not at the prestigious Hesperus facility. A varied weapons mix makes the Uziel an excellent trooper 'Mech.", "The Uziel is built on a Foundation E50 Endo Steel chassis that has a GM 300 XL engine that provides the 'Mech with a top speed of 97.2 km/h. The 'Mech's mobility is enhanced with six Rawlings 50 jump jets that allow the 'Mech to jump up to one hundred and eighty meters. The Uziel is armored with eight tons of Maximillian 100 armor that gives the Uziel adequate protection from enemy fire. To dissipate the heat produced by the 'Mech's weapons, it carries eleven double heat sinks.", "Based on the original prototype of the Uziel developed in 3063, the 2S carries a pair of PPCs as its primary weapons for long range combat. A SRM-6 launcher provides close combat capabilities and a pair of Machine Guns provide anti-infantry capabilities. A Beagle Active Probe allows the 'Mech to detect hidden units and protects the Uziel from ambushes.", None);