INSERT INTO Chassis (chassis_id, chassis_name, model, mul_id, mass, role, config, techbase, era, rules_level, source) VALUES (114625, 'Uziel', 'UZL-3S', '5332', None, 'Striker', 'Biped', None, None, None, None);
INSERT INTO Configuration (config_id, chassis_id, engine, structure, myomer, heat_sinks, walk_mp, jump_mp) VALUES (114625, 114625, None, None, None, None, None, None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1146251, 114625, 'Large Pulse Laser', 'Left Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1146252, 114625, 'LB 2-X AC', 'Right Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1146253, 114625, 'ER Medium Laser', 'Right Arm', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1146254, 114625, 'ER Small Laser', 'Left Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1146255, 114625, 'ER Small Laser', 'Right Torso', None);
INSERT INTO Weapons (weapon_id, chassis_id, weapon_name, location, ammo) VALUES (1146256, 114625, 'SRM 6', 'Center Torso', None);
INSERT INTO Quirks (quirk_id, chassis_id, quirk_name) VALUES (1146251, 114625, 'cowl');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146251, 114625, 'Left Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146252, 114625, 'Left Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146253, 114625, 'Left Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146254, 114625, 'Left Arm', 'ISLargePulseLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146255, 114625, 'Left Arm', 'ISLargePulseLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146256, 114625, 'Left Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146257, 114625, 'Left Arm', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146258, 114625, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146259, 114625, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146260, 114625, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146261, 114625, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146262, 114625, 'Left Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146263, 114625, 'Right Arm', 'Shoulder');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146264, 114625, 'Right Arm', 'Upper Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146265, 114625, 'Right Arm', 'Lower Arm Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146266, 114625, 'Right Arm', 'ISERMediumLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146267, 114625, 'Right Arm', 'ISLBXAC2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146268, 114625, 'Right Arm', 'ISLBXAC2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146269, 114625, 'Right Arm', 'ISLBXAC2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146270, 114625, 'Right Arm', 'ISLBXAC2');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146271, 114625, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146272, 114625, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146273, 114625, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146274, 114625, 'Right Arm', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146275, 114625, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146276, 114625, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146277, 114625, 'Left Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146278, 114625, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146279, 114625, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146280, 114625, 'Left Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146281, 114625, 'Left Torso', 'ISERSmallLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146282, 114625, 'Left Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146283, 114625, 'Left Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146284, 114625, 'Left Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146285, 114625, 'Left Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146286, 114625, 'Left Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146287, 114625, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146288, 114625, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146289, 114625, 'Right Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146290, 114625, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146291, 114625, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146292, 114625, 'Right Torso', 'Jump Jet');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146293, 114625, 'Right Torso', 'ISERSmallLaser');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146294, 114625, 'Right Torso', 'IS Ammo SRM-6');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146295, 114625, 'Right Torso', 'IS LB 2-X AC Ammo');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146296, 114625, 'Right Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146297, 114625, 'Right Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146298, 114625, 'Right Torso', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146299, 114625, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146300, 114625, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146301, 114625, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146302, 114625, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146303, 114625, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146304, 114625, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146305, 114625, 'Center Torso', 'Gyro');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146306, 114625, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146307, 114625, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146308, 114625, 'Center Torso', 'Fusion Engine');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146309, 114625, 'Center Torso', 'SRM 6');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146310, 114625, 'Center Torso', 'SRM 6');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146311, 114625, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146312, 114625, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146313, 114625, 'Head', 'Cockpit');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146314, 114625, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146315, 114625, 'Head', 'Sensors');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146316, 114625, 'Head', 'Life Support');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146317, 114625, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146318, 114625, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146319, 114625, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146320, 114625, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146321, 114625, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146322, 114625, 'Head', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146323, 114625, 'Left Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146324, 114625, 'Left Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146325, 114625, 'Left Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146326, 114625, 'Left Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146327, 114625, 'Left Leg', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146328, 114625, 'Left Leg', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146329, 114625, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146330, 114625, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146331, 114625, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146332, 114625, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146333, 114625, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146334, 114625, 'Left Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146335, 114625, 'Right Leg', 'Hip');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146336, 114625, 'Right Leg', 'Upper Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146337, 114625, 'Right Leg', 'Lower Leg Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146338, 114625, 'Right Leg', 'Foot Actuator');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146339, 114625, 'Right Leg', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146340, 114625, 'Right Leg', 'IS Endo Steel');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146341, 114625, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146342, 114625, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146343, 114625, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146344, 114625, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146345, 114625, 'Right Leg', '-Empty-');
INSERT INTO Actuators_Components (component_id, chassis_id, location, component_name) VALUES (1146346, 114625, 'Right Leg', '-Empty-');
INSERT INTO Manufacturer (manufacturer_id, chassis_id, manufacturer_name, primary_factory, system) VALUES (114625, 114625, 'Defiance Industries', 'Furillo', 'CHASSIS:Foundation E50 Endo Steel');
INSERT INTO History_Overview (history_id, chassis_id, overview, capabilities, deployment, history) VALUES (114625, 114625, "Built at Defiance Industries' Furillo plant, the Uziel is an effective medium 'Mech that is looked down upon by the LAAF simply because it is produced on Furillo and not at the prestigious Hesperus facility. A varied weapons mix makes the Uziel an excellent trooper 'Mech.", "The Uziel is built on a Foundation E50 Endo Steel chassis that has a GM 300 XL engine that provides the 'Mech with a top speed of 97.2 km/h. The 'Mech's mobility is enhanced with six Rawlings 50 jump jets that allow the 'Mech to jump up to one hundred and eighty meters. The Uziel is armored with eight tons of Maximillian 100 armor that gives the Uziel adequate protection from enemy fire. To dissipate the heat produced by the 'Mech's weapons, it carries eleven double heat sinks.", "The Uziel has a wide variety of weapons for a medium 'Mech. For long range combat, the Uziel has a Defiance Shredder LB-X Autocannon/2 that can strike a target at extreme ranges. The rest of the Uziels arsenal is based around shorter range combat with a Thunderbolt-12 Large Pulse Laser and a Defiance Model XII ER Medium Laser for medium range combat. It also has two Diverse Optics Type ER Small Lasers and a Harvester 20K SRM-6 for close combat.", None);